// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui.features

import androidx.compose.runtime.staticCompositionLocalOf

data class BodyExerciseStrings(
    val clapInstructions: String,
    val clapReinforce: String,
    val feetAndHandsReinforce: String,
    val relationshipReinforce: String,
    val feetAndHandsInstructions: String,
    val speedSlow: String,
    val speedFast: String,
    val clapSkinColorHint: String,
    val feetAndHandsSkinColorHint: String,
    val clap: String,
    val steps: String,
    val jumps: String,
    val numberOfClapsStepsJumps: String,
    val clapCounter: String,
    val stepsCounter: String,
    val jumpsCounter: String,
    val clapCompletionMessage: String,
    val exercisingHandsCompletionMessage: String,
    val exercisingFeetAndHandsCompletionMessage: String,
    val exercisingAdditionCompletionMessage: String,
    val exercisingAddition: String,
    val exercisingAdditionInstruction: String,
    val addingTwoNumbers: String,
    val addingLargeNumbers: String,
    val exercisingHands: String,
    val walking: String,
    val exercisingFeetAndHands: String,
    val exercisingMultiplication: String,
    val exercisingMultiplicationL2: String,
    val exercisingMultiplicationL2Description: String,
    val relationship: String,
    val slowly: String,
    val fast: String,
    val doExercise: String,
    val randomly: String,
)

val EnBodyExerciseStrings = BodyExerciseStrings(
    clapInstructions = "Choose the number of times the hands will clap. Then, choose the speed of the claps. Do it yourself with the app.",
    clapReinforce = "To reinforce counting, we are going to do an exercise with our hands. Follow the next instructions and see how numbers are connected to us.",
    feetAndHandsReinforce = "To reinforce counting, we are going to do an exercise with our feet and hands. Follow the next instructions and see how numbers are connected to us.",
    relationshipReinforce = "To reinforce multiplication, we are going to do an exercise relating numbers to body movements. Follow the exercise and see how numbers are connected to us.\n\nThe selector above allows you to choose which multiplication table to practice, and the speed slider adjusts the pace of the movements. Try to do the movements with your own body if you can \u2014 it is a great way to take care of your health as well.",
    feetAndHandsInstructions = "Choose the number of times the feet will step or jump, or the hands will clap. Then, choose the speed. Do it yourself with the app.",
    speedSlow = "Slow",
    speedFast = "Fast",
    clapSkinColorHint = "Also, if you wish, you can change the skin color of the hands to match your own by going to Menu \u2192 Options.",
    feetAndHandsSkinColorHint = "Also, if you wish, you can change the skin color of the hands and feet to match your own by going to Menu \u2192 Options.",
    clap = "Clap",
    steps = "Steps",
    jumps = "Jumps",
    numberOfClapsStepsJumps = "Number of claps, steps, or jumps:",
    clapCounter = "Claps:",
    stepsCounter = "Steps:",
    jumpsCounter = "Jumps:",
    clapCompletionMessage = "Great job! You finished the exercise. Change the number of claps and train again!",
    exercisingHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou finished the exercise!\nAdjust the number of claps, then click 'Play' to workout again!",
    exercisingFeetAndHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou finished the exercise!\nChange the number of claps and train again!",
    exercisingAdditionCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou finished the exercise!\nClick \"New Exercise\" to try a new problem.",
    exercisingAddition = "Exercising addition",
    exercisingAdditionInstruction = "We will add numbers with our body. First, clap the top number, then clap the bottom number. Finally, take steps for the result. If the result is greater than 9, take a jump when reaching 10.",
    addingTwoNumbers = "Adding two numbers",
    addingLargeNumbers = "Adding large numbers",
    exercisingHands = "Exercising hands",
    walking = "Walking",
    exercisingFeetAndHands = "Exercising Feet and Hands",
    exercisingMultiplication = "Exercising Multiplication",
    exercisingMultiplicationL2 = "Exercising Multiplication (L2)",
    exercisingMultiplicationL2Description = "In this exercise, the 4 times table means both hands go up and down. The 5 times table adds a clap after the hands go up and down.\n\nThe up and down movement of both hands also shows that 4 is a multiple of 2, since the 2 movements (up and down) result in 4 total movements.\n\nSelect the multiplication table above, adjust the speed, and click \"Do Exercise\" to start. Try to do the movements with your own body as well!",
    relationship = "Relationship",
    slowly = "Slowly",
    fast = "Fast",
    doExercise = "Do exercise",
    randomly = "Randomly",
)

val PtBodyExerciseStrings = BodyExerciseStrings(
    clapInstructions = "Escolha o n\u00famero de vezes que as m\u00e3os v\u00e3o bater palmas. Depois, escolha a velocidade das palmas. Fa\u00e7a voc\u00ea mesmo com o aplicativo.",
    clapReinforce = "Para refor\u00e7ar a contagem, vamos fazer um exerc\u00edcio com nossas m\u00e3os. Siga as pr\u00f3ximas instru\u00e7\u00f5es e veja como os n\u00fameros est\u00e3o conectados a n\u00f3s.",
    feetAndHandsReinforce = "Para refor\u00e7ar a contagem, vamos fazer um exerc\u00edcio com nossos p\u00e9s e m\u00e3os. Siga as pr\u00f3ximas instru\u00e7\u00f5es e veja como os n\u00fameros est\u00e3o conectados a n\u00f3s.",
    relationshipReinforce = "Para refor\u00e7ar a multiplica\u00e7\u00e3o, vamos fazer um exerc\u00edcio relacionando n\u00fameros a movimentos corporais. Siga o exerc\u00edcio e veja como os n\u00fameros est\u00e3o conectados a n\u00f3s.\n\nO seletor acima permite escolher qual tabuada praticar, e o controle de velocidade ajusta o ritmo dos movimentos. Tente fazer os movimentos com seu pr\u00f3prio corpo se puder \u2014 \u00e9 uma \u00f3tima maneira de cuidar da sua sa\u00fade tamb\u00e9m.",
    feetAndHandsInstructions = "Escolha o n\u00famero de vezes que os p\u00e9s v\u00e3o pisar ou pular, ou as m\u00e3os v\u00e3o bater palmas. Depois, escolha a velocidade. Fa\u00e7a voc\u00ea mesmo com o aplicativo.",
    speedSlow = "Devagar",
    speedFast = "R\u00e1pido",
    clapSkinColorHint = "Al\u00e9m disso, se desejar, voc\u00ea pode alterar a cor da pele das m\u00e3os para combinar com a sua, indo em Menu \u2192 Op\u00e7\u00f5es.",
    feetAndHandsSkinColorHint = "Al\u00e9m disso, se desejar, voc\u00ea pode alterar a cor da pele das m\u00e3os e dos p\u00e9s para combinar com a sua, indo em Menu \u2192 Op\u00e7\u00f5es.",
    clap = "Palmas",
    steps = "Passos",
    jumps = "Pulos",
    numberOfClapsStepsJumps = "N\u00famero de palmas, passos ou pulos:",
    clapCounter = "Palmas:",
    stepsCounter = "Passos:",
    jumpsCounter = "Pulos:",
    clapCompletionMessage = "\u00d3timo trabalho! Voc\u00ea terminou o exerc\u00edcio. Mude o n\u00famero de palmas e treine novamente!",
    exercisingHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea terminou o exerc\u00edcio!\nAjuste o n\u00famero de palmas e clique em 'Play' para treinar novamente!",
    exercisingFeetAndHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea terminou o exerc\u00edcio!\nMude o n\u00famero de palmas e treine novamente!",
    exercisingAdditionCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea terminou o exerc\u00edcio!\nClique em \"Novo Exerc\u00edcio\" para tentar um novo problema.",
    exercisingAddition = "Exercitando adi\u00e7\u00e3o",
    exercisingAdditionInstruction = "Vamos somar n\u00fameros com o nosso corpo. Primeiro, bata palmas para o n\u00famero superior. Depois, bata palmas para o n\u00famero inferior. Por fim, d\u00ea passos para o resultado. Se o resultado for maior que 9, d\u00ea um pulo ao chegar em 10.",
    addingTwoNumbers = "Adicionando dois n\u00fameros",
    addingLargeNumbers = "Adicionando n\u00fameros grandes",
    exercisingHands = "Exercitando as m\u00e3os",
    walking = "Andando",
    exercisingFeetAndHands = "Exercitando P\u00e9s e M\u00e3os",
    exercisingMultiplication = "Exercitando Multiplica\u00e7\u00e3o",
    exercisingMultiplicationL2 = "Exercitando Multiplica\u00e7\u00e3o (L2)",
    exercisingMultiplicationL2Description = "Neste exerc\u00edcio, a tabuada do 4 significa que ambas as m\u00e3os sobem e descem. A tabuada do 5 adiciona uma palma ap\u00f3s as m\u00e3os subirem e descerem.\n\nO movimento de subir e descer de ambas as m\u00e3os tamb\u00e9m mostra que 4 \u00e9 um m\u00faltiplo de 2, j\u00e1 que os 2 movimentos (subir e descer) resultam em 4 movimentos no total.\n\nSelecione a tabuada acima, ajuste a velocidade e clique em \"Fazer Exerc\u00edcio\" para come\u00e7ar. Tente fazer os movimentos com seu pr\u00f3prio corpo tamb\u00e9m!",
    relationship = "Relacionamento",
    slowly = "Devagar",
    fast = "R\u00e1pido",
    doExercise = "Fazer exerc\u00edcio",
    randomly = "Aleat\u00f3rio",
)

val EsBodyExerciseStrings = BodyExerciseStrings(
    clapInstructions = "Elige el n\u00famero de veces que las manos aplaudir\u00e1n. Luego, elige la velocidad de los aplausos. Hazlo t\u00fa mismo con la aplicaci\u00f3n.",
    clapReinforce = "Para reforzar el conteo, vamos a hacer un ejercicio con nuestras manos. Sigue las siguientes instrucciones y observa c\u00f3mo los n\u00fameros est\u00e1n conectados con nosotros.",
    feetAndHandsReinforce = "Para reforzar el conteo, vamos a hacer un ejercicio con nuestros pies y manos. Sigue las siguientes instrucciones y observa c\u00f3mo los n\u00fameros est\u00e1n conectados con nosotros.",
    relationshipReinforce = "Para reforzar la multiplicaci\u00f3n, vamos a hacer un ejercicio relacionando n\u00fameros con movimientos corporales. Sigue el ejercicio y observa c\u00f3mo los n\u00fameros est\u00e1n conectados con nosotros.\n\nEl selector de arriba te permite elegir qu\u00e9 tabla de multiplicar practicar, y el control de velocidad ajusta el ritmo de los movimientos. Intenta hacer los movimientos con tu propio cuerpo si puedes \u2014 tambi\u00e9n es una excelente manera de cuidar tu salud.",
    feetAndHandsInstructions = "Elige el n\u00famero de veces que los pies pisar\u00e1n o saltar\u00e1n, o las manos aplaudir\u00e1n. Luego, elige la velocidad. Hazlo t\u00fa mismo con la aplicaci\u00f3n.",
    speedSlow = "Despacio",
    speedFast = "R\u00e1pido",
    clapSkinColorHint = "Adem\u00e1s, si lo deseas, puedes cambiar el color de piel de las manos para que coincida con la tuya, yendo a Men\u00fa \u2192 Opciones.",
    feetAndHandsSkinColorHint = "Adem\u00e1s, si lo deseas, puedes cambiar el color de piel de las manos y los pies para que coincida con el tuyo, yendo a Men\u00fa \u2192 Opciones.",
    clap = "Aplausos",
    steps = "Pasos",
    jumps = "Saltos",
    numberOfClapsStepsJumps = "N\u00famero de aplausos, pasos o saltos:",
    clapCounter = "Aplausos:",
    stepsCounter = "Pasos:",
    jumpsCounter = "Saltos:",
    clapCompletionMessage = "\u00a1Gran trabajo! Terminaste el ejercicio. \u00a1Cambia el n\u00famero de aplausos y entrena de nuevo!",
    exercisingHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n\u00a1Terminaste el ejercicio!\nAjusta el n\u00famero de aplausos y haz clic en 'Play' para entrenar de nuevo!",
    exercisingFeetAndHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n\u00a1Terminaste el ejercicio!\n\u00a1Cambia el n\u00famero de aplausos y entrena de nuevo!",
    exercisingAdditionCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n\u00a1Terminaste el ejercicio!\nHaz clic en \"Nuevo Ejercicio\" para probar un nuevo problema.",
    exercisingAddition = "Ejercitando suma",
    exercisingAdditionInstruction = "Vamos a sumar n\u00fameros con nuestro cuerpo. Primero, aplaude el n\u00famero superior. Luego, aplaude el n\u00famero inferior. Finalmente, da pasos para el resultado. Si el resultado es mayor que 9, da un salto al llegar a 10.",
    addingTwoNumbers = "Sumando dos n\u00fameros",
    addingLargeNumbers = "Sumando n\u00fameros grandes",
    exercisingHands = "Ejercitando las manos",
    walking = "Caminando",
    exercisingFeetAndHands = "Ejercitando Pies y Manos",
    exercisingMultiplication = "Ejercitando Multiplicaci\u00f3n",
    exercisingMultiplicationL2 = "Ejercitando Multiplicaci\u00f3n (L2)",
    exercisingMultiplicationL2Description = "En este ejercicio, la tabla del 4 significa que ambas manos suben y bajan. La tabla del 5 a\u00f1ade un aplauso despu\u00e9s de que las manos suban y bajen.\n\nEl movimiento de subir y bajar de ambas manos tambi\u00e9n muestra que 4 es un m\u00faltiplo de 2, ya que los 2 movimientos (subir y bajar) resultan en 4 movimientos en total.\n\nSelecciona la tabla arriba, ajusta la velocidad y haz clic en \"Hacer Ejercicio\" para comenzar. \u00a1Intenta hacer los movimientos con tu propio cuerpo tambi\u00e9n!",
    relationship = "Relaci\u00f3n",
    slowly = "Despacio",
    fast = "R\u00e1pido",
    doExercise = "Hacer ejercicio",
    randomly = "Aleatorio",
)

val LocalBodyExerciseStrings = staticCompositionLocalOf { EnBodyExerciseStrings }

fun bodyExerciseStringsForLanguage(language: String): BodyExerciseStrings = when (language) {
    "pt-BR" -> PtBodyExerciseStrings
    "es-ES" -> EsBodyExerciseStrings
    else -> EnBodyExerciseStrings
}
