// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui.features

import androidx.compose.runtime.staticCompositionLocalOf

data class CarryOrNotCarryScreenStrings(
    // Intro screen
    val title: String,
    val intro: String,
    val stepsHeading: String,
    val step1Title: String,
    val step1Body: String,
    val step2Title: String,
    val step2Body: String,
    val step3Title: String,
    val step3Body: String,
    val start: String,
    // Game screen
    val levelTemplate: String,
    val questionTemplate: String,
    val orderUnits: String,
    val orderTens: String,
    val orderHundreds: String,
    val orderThousands: String,
    val orderTenThousands: String,
    val carry: String,
    val notCarry: String,
    val complementToTen: String,
    val squaresCaption: String,
    val incomingNote: String,
    val msgCarryCorrect: String,
    val msgNotCorrect: String,
    val msgCarryWrong: String,
    val msgNotWrong: String,
    val nextColumn: String,
    val nextLevel: String,
    val playAgain: String,
    val allLevelsDone: String,
)

val EnCarryOrNotCarryScreenStrings = CarryOrNotCarryScreenStrings(
    title = "Carry or Not Carry?",
    intro = "In every level the question is the same: does this column carry 1 to the next order? The game always moves column by column, starting from the units.",
    stepsHeading = "To answer, follow three steps:",
    step1Title = "Value already in the column",
    step1Body = "Take the digit of the top number and add the 1 carried from the column on the right, if there is one. The game shows this total.",
    step2Title = "Complement to 10",
    step2Body = "Ask how much is missing to reach 10. That amount is the complement.",
    step3Title = "Digit you are adding",
    step3Body = "If it is smaller than the complement, the total stays below 10 and the column does not carry. If it is equal to or greater than the complement, the total reaches 10 and the column carries 1 to the next column.",
    start = "Start",
    levelTemplate = "Level %d of 4",
    questionTemplate = "Does the %s column carry 1 to the next order?",
    orderUnits = "Units",
    orderTens = "Tens",
    orderHundreds = "Hundreds",
    orderThousands = "Thousands",
    orderTenThousands = "Ten thousands",
    carry = "Carry",
    notCarry = "Not carry",
    complementToTen = "Complement to 10",
    squaresCaption = "%d + %d = 10",
    incomingNote = "The 1 carried from the previous column is added: %d + 1 = %d.",
    msgCarryCorrect = "Correct! The complement of %1\$d to 10 is %3\$d. Since %2\$d is equal to or greater than %3\$d, %1\$d + %2\$d = %4\$d reaches 10, so the %5\$s column carries 1 to the next order.",
    msgNotCorrect = "Correct! The complement of %1\$d to 10 is %3\$d. Since %2\$d is less than %3\$d, %1\$d + %2\$d = %4\$d stays below 10, so the %5\$s column does not carry.",
    msgCarryWrong = "Not yet. The complement of %1\$d to 10 is %3\$d. Since %2\$d is less than %3\$d, %1\$d + %2\$d = %4\$d stays below 10. The %5\$s column does not carry.",
    msgNotWrong = "Not yet. The complement of %1\$d to 10 is %3\$d. Since %2\$d is equal to or greater than %3\$d, %1\$d + %2\$d = %4\$d reaches 10. The %5\$s column carries 1 to the next order.",
    nextColumn = "Next column",
    nextLevel = "Next level",
    playAgain = "Play again",
    allLevelsDone = "\uD83C\uDF89 Well done! You finished all four levels. \uD83C\uDF89",
)

val PtCarryOrNotCarryScreenStrings = CarryOrNotCarryScreenStrings(
    title = "Vai um ou n\u00e3o vai?",
    intro = "Em cada n\u00edvel a pergunta \u00e9 a mesma: esta coluna leva 1 para a ordem seguinte? O jogo avan\u00e7a sempre coluna por coluna, come\u00e7ando pelas unidades.",
    stepsHeading = "Para responder, siga tr\u00eas passos:",
    step1Title = "O valor que a coluna j\u00e1 tem",
    step1Body = "Some o d\u00edgito do primeiro n\u00famero com o 1 que veio da coluna da direita, se houver. O jogo mostra esse total.",
    step2Title = "O complemento at\u00e9 10",
    step2Body = "Pergunte quanto falta para chegar a 10. Essa quantidade \u00e9 o complemento.",
    step3Title = "O d\u00edgito que estamos somando",
    step3Body = "Se for menor que o complemento, o total fica abaixo de 10 e a coluna n\u00e3o leva nada. Se for igual ou maior que o complemento, o total alcan\u00e7a 10 e a coluna leva 1 para a coluna seguinte.",
    start = "Come\u00e7ar",
    levelTemplate = "N\u00edvel %d de 4",
    questionTemplate = "A coluna de %s leva 1 para a ordem seguinte?",
    orderUnits = "Unidades",
    orderTens = "Dezenas",
    orderHundreds = "Centenas",
    orderThousands = "Milhares",
    orderTenThousands = "Dezenas de milhar",
    carry = "Vai um",
    notCarry = "N\u00e3o vai um",
    complementToTen = "Complemento at\u00e9 10",
    squaresCaption = "%d + %d = 10",
    incomingNote = "Somamos o 1 que veio da coluna anterior: %d + 1 = %d.",
    msgCarryCorrect = "Correto! O complemento de %1\$d at\u00e9 10 \u00e9 %3\$d. Como %2\$d \u00e9 igual ou maior que %3\$d, %1\$d + %2\$d = %4\$d alcan\u00e7a 10, ent\u00e3o a coluna de %5\$s leva 1 para a ordem seguinte.",
    msgNotCorrect = "Correto! O complemento de %1\$d at\u00e9 10 \u00e9 %3\$d. Como %2\$d \u00e9 menor que %3\$d, %1\$d + %2\$d = %4\$d fica abaixo de 10, ent\u00e3o a coluna de %5\$s n\u00e3o leva.",
    msgCarryWrong = "Ainda n\u00e3o. O complemento de %1\$d at\u00e9 10 \u00e9 %3\$d. Como %2\$d \u00e9 menor que %3\$d, %1\$d + %2\$d = %4\$d fica abaixo de 10. A coluna de %5\$s n\u00e3o leva.",
    msgNotWrong = "Ainda n\u00e3o. O complemento de %1\$d at\u00e9 10 \u00e9 %3\$d. Como %2\$d \u00e9 igual ou maior que %3\$d, %1\$d + %2\$d = %4\$d alcan\u00e7a 10. A coluna de %5\$s leva 1 para a ordem seguinte.",
    nextColumn = "Pr\u00f3xima coluna",
    nextLevel = "Pr\u00f3ximo n\u00edvel",
    playAgain = "Jogar novamente",
    allLevelsDone = "\uD83C\uDF89 Muito bem! Voc\u00ea concluiu os quatro n\u00edveis. \uD83C\uDF89",
)

val EsCarryOrNotCarryScreenStrings = CarryOrNotCarryScreenStrings(
    title = "\u00bfSe lleva o no se lleva?",
    intro = "En cada nivel la pregunta es la misma: \u00bfesta columna lleva 1 al siguiente orden? El juego avanza siempre columna por columna, empezando por las unidades.",
    stepsHeading = "Para responder, sigue tres pasos:",
    step1Title = "Valor que ya tiene la columna",
    step1Body = "Toma el d\u00edgito del primer n\u00famero y suma el 1 que se llev\u00f3 de la columna de la derecha, si lo hay. El juego muestra ese total.",
    step2Title = "Complemento hasta 10",
    step2Body = "Pregunta cu\u00e1nto falta para llegar a 10. Esa cantidad es el complemento.",
    step3Title = "El d\u00edgito que sumamos",
    step3Body = "Si es menor que el complemento, el total se queda por debajo de 10 y la columna no se lleva nada. Si es igual o mayor que el complemento, el total alcanza 10 y la columna se lleva 1 a la columna siguiente.",
    start = "Empezar",
    levelTemplate = "Nivel %d de 4",
    questionTemplate = "\u00bfLa columna de %s lleva 1 al siguiente orden?",
    orderUnits = "Unidades",
    orderTens = "Decenas",
    orderHundreds = "Centenas",
    orderThousands = "Millares",
    orderTenThousands = "Decenas de millar",
    carry = "Se lleva",
    notCarry = "No se lleva",
    complementToTen = "Complemento hasta 10",
    squaresCaption = "%d + %d = 10",
    incomingNote = "Se suma el 1 que se llev\u00f3 de la columna anterior: %d + 1 = %d.",
    msgCarryCorrect = "\u00a1Correcto! El complemento de %1\$d hasta 10 es %3\$d. Como %2\$d es igual o mayor que %3\$d, %1\$d + %2\$d = %4\$d alcanza 10, as\u00ed que la columna de %5\$s lleva 1 al siguiente orden.",
    msgNotCorrect = "\u00a1Correcto! El complemento de %1\$d hasta 10 es %3\$d. Como %2\$d es menor que %3\$d, %1\$d + %2\$d = %4\$d se queda por debajo de 10, as\u00ed que la columna de %5\$s no lleva.",
    msgCarryWrong = "Todav\u00eda no. El complemento de %1\$d hasta 10 es %3\$d. Como %2\$d es menor que %3\$d, %1\$d + %2\$d = %4\$d se queda por debajo de 10. La columna de %5\$s no lleva.",
    msgNotWrong = "Todav\u00eda no. El complemento de %1\$d hasta 10 es %3\$d. Como %2\$d es igual o mayor que %3\$d, %1\$d + %2\$d = %4\$d alcanza 10. La columna de %5\$s lleva 1 al siguiente orden.",
    nextColumn = "Siguiente columna",
    nextLevel = "Siguiente nivel",
    playAgain = "Jugar de nuevo",
    allLevelsDone = "\uD83C\uDF89 \u00a1Muy bien! Terminaste los cuatro niveles. \uD83C\uDF89",
)

val LocalCarryOrNotCarryScreenStrings = staticCompositionLocalOf { EnCarryOrNotCarryScreenStrings }

fun carryOrNotCarryScreenStringsForLanguage(language: String): CarryOrNotCarryScreenStrings = when (language) {
    "pt-BR" -> PtCarryOrNotCarryScreenStrings
    "es-ES" -> EsCarryOrNotCarryScreenStrings
    else -> EnCarryOrNotCarryScreenStrings
}
