// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui.features

import androidx.compose.runtime.staticCompositionLocalOf

data class HubTitleStrings(
    val aRoadToSomewhere: String,
    val birth: String,
    val death: String,
    val firstSteps: String,
    val workout: String,
    val abacus: String,
    val iDontKnow: String,
    val iAmNotLikeYou: String,
    val myHands: String,
    val myBody: String,
    val drawing: String,
    val numbers: String,
    val sequenceGame: String,
    val familyPart1: String,
    val aboutUs: String,
    val aboutDescription: String,
    val isItFree: String,
    val isItFreeContent: String,
    val isItFreeDonateCall: String,
    val isItFreeFollowPrefix: String,
    val isItFreeFollowSuffix: String,
    val history: String,
    val naturalFamiliesPart2: String,
    val goingToInfinity: String,
    val whereAreWeFrom: String,
    val returning: String,
    val tomokoHoult: String,
    val aPal: String,
    val jessicaAmarteifio: String,
    val langEnUs: String,
    val langPtBr: String,
    val langEsEs: String,
    val congratulationTitle: String,
    val congratulationMessage: String,
    val whoWalkFirst: String,
    val whoWalkFirstButton: String,
)

val EnHubTitleStrings = HubTitleStrings(
    aRoadToSomewhere = "A Road to Somewhere",
    birth = "Birth",
    death = "Death",
    firstSteps = "First Steps (Counting)",
    workout = "Workout",
    abacus = "Abacus",
    iDontKnow = "I Know that I Know Nothing",
    iAmNotLikeYou = "I Am (Not) Like You",
    myHands = "My Hands",
    myBody = "My Body",
    drawing = "Drawing and Couting",
    numbers = "Numbers",
    sequenceGame = "Sequence Game",
    familyPart1 = "Family (Part 1)",
    aboutUs = "About Us",
    aboutDescription = "History Tracers is an open source project created to help people understand content instead of only exercising memorization.\n\nJoin our social network and share with us what subject you would like to have in all History Tracers apps.",
    isItFree = "Is It Free?",
    isItFreeContent = "This project is not only free, but we also share the code with you, allowing you to learn how to create it as well.\n\nBut the fact that it is free does not mean it has no costs for us. We have expenses to maintain it, and it can grow faster when you contribute with ideas and, if possible, with financial support.",
    isItFreeDonateCall = "To support us, you can use one of our donation channels:",
    isItFreeFollowPrefix = "If you cannot, you do not need to feel bad, go to section below and follow us:",
    isItFreeFollowSuffix = "",
    history = "History",
    naturalFamiliesPart2 = "Natural Families (Part 2)",
    goingToInfinity = "Toward Infinity",
    whereAreWeFrom = "Where Are We From?",
    returning = "Returning",
    tomokoHoult = "Tomoko Hoult",
    aPal = "A-PAL",
    jessicaAmarteifio = "Jessica Amarteifio",
    langEnUs = "English (US)",
    langPtBr = "Portugu\u00eas (BR)",
    langEsEs = "Espa\u00f1ol (ES)",
    congratulationTitle = "Congratulations!",
    congratulationMessage = "Congratulations on reaching this level! The previous classes are not locked, and you will not receive fewer points for studying them again. Every person has their own time to learn, and we respect that.\n\nWe are going to give you 10 points for reaching this level for the first time by completing everything before.\n\nEnjoy your own way of learning and your life, respecting yourself!",
    whoWalkFirst = "Who Walked First?",
    whoWalkFirstButton = "?",
)

val PtHubTitleStrings = HubTitleStrings(
    aRoadToSomewhere = "Uma estrada para algum lugar",
    birth = "Nascimento",
    death = "Morte",
    firstSteps = "Primeiros Passos (Contando)",
    workout = "Exerc\u00edcio",
    abacus = "\u00c1baco",
    iDontKnow = "S\u00f3 sei que nada sei...",
    iAmNotLikeYou = "Eu (n\u00e3o) sou como voc\u00ea",
    myHands = "Minhas m\u00e3os",
    myBody = "Meu corpo",
    drawing = "Desenho e Contagem",
    numbers = "N\u00fameros",
    sequenceGame = "Jogo da sequ\u00eancia",
    familyPart1 = "Fam\u00edlia (Parte 1)",
    aboutUs = "Sobre n\u00f3s",
    aboutDescription = "History Tracers \u00e9 um projeto de c\u00f3digo aberto criado para ajudar as pessoas a compreender o conte\u00fado, em vez de apenas exercitar a memoriza\u00e7\u00e3o.\n\nJunte-se \u00e0 nossa rede social e compartilhe conosco qual assunto voc\u00ea gostaria de ter em todos os aplicativos History Tracers.",
    isItFree = "\u00c9 gratuito?",
    isItFreeContent = "Este projeto n\u00e3o \u00e9 apenas gratuito, mas tamb\u00e9m compartilhamos o c\u00f3digo com voc\u00ea, permitindo que aprenda a cri\u00e1-lo tamb\u00e9m.\n\nMas o fato de ser gratuito n\u00e3o significa que n\u00e3o tenha custos para n\u00f3s. Temos despesas para mant\u00ea-lo, e ele pode crescer mais r\u00e1pido quando voc\u00ea contribui com ideias e, se poss\u00edvel, com apoio financeiro.",
    isItFreeDonateCall = "Para nos apoiar, use um de nossos canais de doa\u00e7\u00e3o:",
    isItFreeFollowPrefix = "Se n\u00e3o puder, n\u00e3o precisa se sentir mal, v\u00e1 at\u00e9 a se\u00e7\u00e3o abaixo e siga-nos:",
    isItFreeFollowSuffix = "",
    history = "Hist\u00f3ria",
    naturalFamiliesPart2 = "Fam\u00edlias Naturais (Parte 2)",
    goingToInfinity = "Indo ao infinito",
    whereAreWeFrom = "De onde somos?",
    returning = "Retornando",
    tomokoHoult = "Tomoko Hoult",
    aPal = "A-PAL",
    jessicaAmarteifio = "Jessica Amarteifio",
    langEnUs = "Ingl\u00eas (EUA)",
    langPtBr = "Portugu\u00eas (BR)",
    langEsEs = "Espanhol (ES)",
    congratulationTitle = "Parab\u00e9ns!",
    congratulationMessage = "Parab\u00e9ns por alcan\u00e7ar este n\u00edvel! As aulas anteriores n\u00e3o est\u00e3o bloqueadas e voc\u00ea n\u00e3o receber\u00e1 menos pontos por estud\u00e1-las novamente. Cada pessoa tem seu pr\u00f3prio tempo para aprender, e n\u00f3s respeitamos isso.\n\nVamos dar a voc\u00ea 10 pontos por alcan\u00e7ar este n\u00edvel pela primeira vez, fazendo tudo o que veio antes.\n\nAproveite seu pr\u00f3prio jeito de aprender e sua vida, respeitando a si mesmo!",
    whoWalkFirst = "Quem andou primeiro?",
    whoWalkFirstButton = "?",
)

val EsHubTitleStrings = HubTitleStrings(
    aRoadToSomewhere = "Un camino a alg\u00fan lugar",
    birth = "Nacimiento",
    death = "Muerte",
    firstSteps = "Primeros Pasos (Contando)",
    workout = "Ejercicio",
    abacus = "\u00c1baco",
    iDontKnow = "Solo s\u00e9 que no s\u00e9 nada...",
    iAmNotLikeYou = "Yo (no) soy como t\u00fa",
    myHands = "Mis manos",
    myBody = "Mi cuerpo",
    drawing = "Dibujo y Conteo",
    numbers = "N\u00fameros",
    sequenceGame = "Juego de secuencia",
    familyPart1 = "Familia (Parte 1)",
    aboutUs = "Sobre nosotros",
    aboutDescription = "History Tracers es un proyecto de c\u00f3digo abierto creado para ayudar a las personas a comprender el contenido, en lugar de solo ejercitar la memorizaci\u00f3n.\n\n\u00danete a nuestra red social y comparte con nosotros qu\u00e9 tema te gustar\u00eda tener en todas las aplicaciones de History Tracers.",
    isItFree = "\u00bfEs gratuito?",
    isItFreeContent = "Este proyecto no solo es gratuito, sino que tambi\u00e9n compartimos el c\u00f3digo contigo, permiti\u00e9ndote aprender a crearlo tambi\u00e9n.\n\nPero el hecho de que sea gratuito no significa que no tenga costos para nosotros. Tenemos gastos para mantenerlo, y puede crecer m\u00e1s r\u00e1pido cuando contribuyes con ideas y, si es posible, con apoyo financiero.",
    isItFreeDonateCall = "Para apoyarnos, usa uno de nuestros canales de donaci\u00f3n:",
    isItFreeFollowPrefix = "Si no puedes, no te sientas mal, ve a la secci\u00f3n de abajo y s\u00edguenos:",
    isItFreeFollowSuffix = "",
    history = "Historia",
    naturalFamiliesPart2 = "Familias Naturales (Parte 2)",
    goingToInfinity = "Yendo al infinito",
    whereAreWeFrom = "\u00bfDe d\u00f3nde somos?",
    returning = "Regresando",
    tomokoHoult = "Tomoko Hoult",
    aPal = "A-PAL",
    jessicaAmarteifio = "Jessica Amarteifio",
    langEnUs = "Ingl\u00e9s (EE. UU.)",
    langPtBr = "Portugu\u00e9s (BR)",
    langEsEs = "Espa\u00f1ol (ES)",
    congratulationTitle = "\u00a1Felicitaciones!",
    congratulationMessage = "\u00a1Felicitaciones por alcanzar este nivel! Las clases anteriores no est\u00e1n bloqueadas y no recibir\u00e1s menos puntos por estudiarlas de nuevo. Cada persona tiene su propio tiempo para aprender, y respetamos eso.\n\nTe vamos a dar 10 puntos por alcanzar este nivel por primera vez, habiendo hecho todo lo anterior.\n\n\u00a1Disfruta tu propia forma de aprender y tu vida, respet\u00e1ndote a ti mismo!",
    whoWalkFirst = "\u00bfQui\u00e9n camin\u00f3 primero?",
    whoWalkFirstButton = "\u00bf?",
)

val LocalHubTitleStrings = staticCompositionLocalOf { EnHubTitleStrings }

fun hubTitleStringsForLanguage(language: String): HubTitleStrings = when (language) {
    "pt-BR" -> PtHubTitleStrings
    "es-ES" -> EsHubTitleStrings
    else -> EnHubTitleStrings
}
