// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui.features

import androidx.compose.runtime.staticCompositionLocalOf

data class MwStrings(
    val multiplyingWithAbacus: String,
    val multiplyingWithAbacusDescription: String,
    val multiplyingWithAbacusInstruction: String,
    val mwStepPrefix: String,
    val mwWelcomeMessage: String,
    val mwStepWriteFirst: String,
    val mwStepAddContribution: String,
    val mwUnitsProductHeader: String,
    val mwStepAdd: String,
    val mwStepCarry: String,
    val mwStepFinal: String,
    val mwCongratulations: String,
    val mwStepStatus: String,
    val mwCorrectMessage: String,
    val mwPerfectMessage: String,
    val mwLastLevelMessage: String,
    val mw2Title: String,
    val mw2Description: String,
    val mw3Title: String,
    val mwlInstruction: String,
    val mwlShiftInstruction: String,
    val mwlStoreInstruction: String,
    val mwlResetInstruction: String,
    val mwlAddStoredPrefix: String,
    val mwlLastLevelMessage: String,
    val mwlAddDigitTo: String,
    val mwlAddCarrying: String,
    val mwlStoredLabel: String,
    val mw2Instruction: String,
    val mw2StepWriteFirst: String,
    val mw2LastLevelMessage: String,
)

val EnMwStrings = MwStrings(
    multiplyingWithAbacus = "12 x 3",
    multiplyingWithAbacusDescription = "Multiplying with Abacus",
    multiplyingWithAbacusInstruction = "Set the abacus to show each intermediate multiplication result by tapping the beads, following the step-by-step instructions below. Complete all steps to finish the multiplication.",
    mwStepPrefix = "\uD83E\uDDEE ",
    mwWelcomeMessage = "Click 'New Exercise' to start. Follow the instructions to arrange the abacus.",
    mwStepWriteFirst = "Step 1: Multiply the tens of %d by %d: %d \u00D7 %d = %d. Set the abacus to show %d.",
    mwStepAddContribution = "%d \u00D7 %d = %d",
    mwUnitsProductHeader = "%d \u00D7 %d = %d. Therefore, ",
    mwStepAdd = "Add %d to the %s column. After this addition, the abacus should show %d.",
    mwStepCarry = "Carrying: Adding %d to %s gives %d + %d = %d (\u2265 10). Remove complement %d from %s and add 1 to %s. After these movements, the abacus should show %d.",
    mwStepFinal = "Final: %d \u00D7 %d = %d. The abacus should show this product!",
    mwCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou calculated %d \u00D7 %d = %d\nClick 'New exercise' to practice more!",
    mwStepStatus = "Step %d/%d",
    mwCorrectMessage = "\u2705 Correct! Click 'Next step' to continue.",
    mwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFECT! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u00D7 %d = %d\nGreat job using the abacus!",
    mwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered multiplication by %d! Click \"New exercise\" to start again at level 1.",
    mw2Title = "Multiplying with Abacus (Level 2)",
    mw2Description = "Multiplying with Abacus (Level 2)",
    mw3Title = "Multiplying without Limits",
    mwlInstruction = "Set the abacus to show each intermediate product by tapping the beads. First multiply by the tens digit, then multiply by the ones digit and add to the result.",
    mwlShiftInstruction = "Shift left: %d \u2192 %d",
    mwlStoreInstruction = "I am storing %d to be added later",
    mwlResetInstruction = "Reset the abacus to 0. Click the \"Reset to 0\" button.",
    mwlAddStoredPrefix = "Add stored %d: ",
    mwlAddDigitTo = "Add to the %s: Add %d to the %s column. After this addition, the abacus should show %d.",
    mwlAddCarrying = "Carrying 1: Adding %d to %s gives %d + %d = %d. Remove the complement %d from the %s column. Add 1 to the %s column. After these movements, the abacus should show %d.",
    mwlStoredLabel = "Stored: %d",
    mwlLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered two-digit multiplication! Click \"New exercise\" to start again at level 1.",
    mw2Instruction = "Set the abacus to show each intermediate multiplication result by tapping the beads, following the step-by-step instructions below. Complete all steps to finish the multiplication.",
    mw2StepWriteFirst = "Step 1: %d \u00D7 %d = %d. Set the abacus to show %d.",
    mw2LastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered all 8 levels! Click \"New exercise\" to start again at level 1.",
)

val PtMwStrings = MwStrings(
    multiplyingWithAbacus = "12 x 3",
    multiplyingWithAbacusDescription = "Multiplicando com \u00c1baco",
    multiplyingWithAbacusInstruction = "Configure o \u00e1baco para mostrar cada resultado intermedi\u00e1rio da multiplica\u00e7\u00e3o tocando nas contas, seguindo as instru\u00e7\u00f5es passo a passo abaixo. Complete todos os passos para finalizar a multiplica\u00e7\u00e3o.",
    mwStepPrefix = "\uD83E\uDDEE ",
    mwWelcomeMessage = "Clique em 'Novo Exerc\u00edcio' para iniciar. Siga as instru\u00e7\u00f5es para organizar o \u00e1baco.",
    mwStepWriteFirst = "Passo 1: Multiplique as dezenas de %d por %d: %d \u00D7 %d = %d. Coloque o \u00e1baco para mostrar %d.",
    mwStepAddContribution = "%d \u00D7 %d = %d",
    mwUnitsProductHeader = "%d \u00D7 %d = %d. Portanto, ",
    mwStepAdd = "Adicione %d \u00e0 coluna %s. Ap\u00f3s esta adi\u00e7\u00e3o, o \u00e1baco deve mostrar %d.",
    mwStepCarry = "Levando 1: Adicionando %d a %s temos %d + %d = %d (\u2265 10). Remova o complemento %d de %s e adicione 1 a %s. Ap\u00f3s esses movimentos, o \u00e1baco deve mostrar %d.",
    mwStepFinal = "Final: %d \u00D7 %d = %d. O \u00e1baco deve mostrar este produto!",
    mwCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea calculou %d \u00D7 %d = %d\nClique em 'Novo exerc\u00edcio' para praticar mais!",
    mwStepStatus = "Passo %d/%d",
    mwCorrectMessage = "\u2705 Correto! Clique em 'Pr\u00f3ximo passo' para continuar.",
    mwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFEITO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u00D7 %d = %d\n\u00d3timo trabalho usando o \u00e1baco!",
    mwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou a multiplica\u00e7\u00e3o por %d! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
    mw2Title = "Multiplicando com \u00c1baco (N\u00edvel 2)",
    mw2Description = "Multiplicando com \u00c1baco (N\u00edvel 2)",
    mw3Title = "Multiplicando sem Limites",
    mwlInstruction = "Configure o \u00e1baco para mostrar cada produto intermedi\u00e1rio tocando nas contas. Primeiro multiplique pelo d\u00edgito das dezenas, depois multiplique pelo d\u00edgito das unidades e adicione ao resultado.",
    mwlShiftInstruction = "Desloque \u00e0 esquerda: %d \u2192 %d",
    mwlStoreInstruction = "Estou armazenando %d para ser adicionado depois",
    mwlResetInstruction = "Reinicialize o \u00e1baco para 0. Clique no bot\u00e3o \"Reset to 0\".",
    mwlAddStoredPrefix = "Adicione o armazenado %d: ",
    mwlAddDigitTo = "Adicione \u00e0 %s: Adicione %d \u00e0 coluna %s. Ap\u00f3s esta adi\u00e7\u00e3o, o \u00e1baco deve mostrar %d.",
    mwlAddCarrying = "Carregando 1: Adicionando %d \u00e0 %s resulta em %d + %d = %d. Remova o complemento %d da coluna %s. Adicione 1 \u00e0 coluna %s. Ap\u00f3s esses movimentos, o \u00e1baco deve mostrar %d.",
    mwlStoredLabel = "Armazenado: %d",
    mwlLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou a multiplica\u00e7\u00e3o por dois d\u00edgitos! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
    mw2Instruction = "Configure o \u00e1baco para mostrar cada resultado intermedi\u00e1rio da multiplica\u00e7\u00e3o tocando nas contas, seguindo as instru\u00e7\u00f5es passo a passo abaixo. Complete todos os passos para finalizar a multiplica\u00e7\u00e3o.",
    mw2StepWriteFirst = "Passo 1: %d \u00D7 %d = %d. Coloque o \u00e1baco para mostrar %d.",
    mw2LastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou todos os 8 n\u00edveis! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
)

val EsMwStrings = MwStrings(
    multiplyingWithAbacus = "12 x 3",
    multiplyingWithAbacusDescription = "Multiplicando con \u00c1baco",
    multiplyingWithAbacusInstruction = "Configura el \u00e1baco para mostrar cada resultado intermedio de la multiplicaci\u00f3n tocando las cuentas, siguiendo las instrucciones paso a paso a continuaci\u00f3n. Completa todos los pasos para finalizar la multiplicaci\u00f3n.",
    mwStepPrefix = "\uD83E\uDDEE ",
    mwWelcomeMessage = "Haz clic en 'Nuevo Ejercicio' para comenzar. Sigue las instrucciones para organizar el \u00e1baco.",
    mwStepWriteFirst = "Paso 1: Multiplica las decenas de %d por %d: %d \u00D7 %d = %d. Coloca el \u00e1baco para mostrar %d.",
    mwStepAddContribution = "%d \u00D7 %d = %d",
    mwUnitsProductHeader = "%d \u00D7 %d = %d. Por lo tanto, ",
    mwStepAdd = "A\u00f1ade %d a la columna %s. Despu\u00e9s de esta suma, el \u00e1baco debe mostrar %d.",
    mwStepCarry = "Llevando 1: Al a\u00f1adir %d a %s tenemos %d + %d = %d (\u2265 10). Quita el complemento %d de %s y a\u00f1ade 1 a %s. Despu\u00e9s de estos movimientos, el \u00e1baco debe mostrar %d.",
    mwStepFinal = "Final: %d \u00D7 %d = %d. \u00a1El \u00e1baco debe mostrar este producto!",
    mwCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nHas calculado %d \u00D7 %d = %d\n\u00a1Haz clic en 'Nuevo ejercicio' para practicar m\u00e1s!",
    mwStepStatus = "Paso %d/%d",
    mwCorrectMessage = "\u2705 \u00a1Correcto! Haz clic en 'Siguiente paso' para continuar.",
    mwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1PERFECTO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u00D7 %d = %d\n\u00a1Gran trabajo usando el \u00e1baco!",
    mwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste la multiplicaci\u00f3n por %d! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
    mw2Title = "Multiplicando con \u00c1baco (Nivel 2)",
    mw2Description = "Multiplicando con \u00c1baco (Nivel 2)",
    mw3Title = "Multiplicando sin L\u00edmites",
    mwlInstruction = "Configura el \u00e1baco para mostrar cada producto intermedio tocando las cuentas. Primero multiplica por el d\u00edgito de las decenas, luego multiplica por el d\u00edgito de las unidades y suma al resultado.",
    mwlShiftInstruction = "Desplaza a la izquierda: %d \u2192 %d",
    mwlStoreInstruction = "Estoy guardando %d para agregarse despu\u00e9s",
    mwlResetInstruction = "Reinicia el \u00e1baco a 0. Haz clic en el bot\u00f3n \"Reset to 0\".",
    mwlAddStoredPrefix = "Suma el guardado %d: ",
    mwlAddDigitTo = "Agrega a %s: Agrega %d a la columna %s. Despu\u00e9s de esta suma, el \u00e1baco debe mostrar %d.",
    mwlAddCarrying = "Llevando 1: Sumando %d a %s da %d + %d = %d. Retira el complemento %d de la columna %s. Agrega 1 a la columna %s. Despu\u00e9s de estos movimientos, el \u00e1baco debe mostrar %d.",
    mwlStoredLabel = "Guardado: %d",
    mwlLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste la multiplicaci\u00f3n por dos d\u00edgitos! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
    mw2Instruction = "Configura el \u00e1baco para mostrar cada resultado intermedio de la multiplicaci\u00f3n tocando las cuentas, siguiendo las instrucciones paso a paso a continuaci\u00f3n. Completa todos los pasos para finalizar la multiplicaci\u00f3n.",
    mw2StepWriteFirst = "Paso 1: %d \u00D7 %d = %d. Coloca el \u00e1baco para mostrar %d.",
    mw2LastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste los 8 niveles! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
)

val LocalMwStrings = staticCompositionLocalOf { EnMwStrings }

fun mwStringsForLanguage(language: String): MwStrings = when (language) {
    "pt-BR" -> PtMwStrings
    "es-ES" -> EsMwStrings
    else -> EnMwStrings
}
