// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui.features

import androidx.compose.runtime.staticCompositionLocalOf

data class SequenceGameOrdersScreenStrings(
    val title: String,
    val instruction: String,
    val units: String,
    val tens: String,
    val hundreds: String,
    val thousands: String,
    val tenThousands: String,
    val hundredThousands: String,
    val millions: String,
    val tenMillions: String,
    val hundredMillions: String,
    val billions: String,
    val newGame: String,
    val completionMessage: String,
    val numberDescUnits: String,
    val numberDescTens: String,
    val numberDescHundreds: String,
    val numberDescThousands: String,
    val numberDescTenThousands: String,
    val numberDescHundredThousands: String,
    val numberDescMillions: String,
    val numberDescTenMillions: String,
    val numberDescHundredMillions: String,
    val numberDescBillions: String,
    val nameDescUnits: String,
    val nameDescTens: String,
    val nameDescHundreds: String,
    val nameDescThousands: String,
    val nameDescTenThousands: String,
    val nameDescHundredThousands: String,
    val nameDescMillions: String,
    val nameDescTenMillions: String,
    val nameDescHundredMillions: String,
    val nameDescBillions: String,
)

val EnSequenceGameOrdersScreenStrings = SequenceGameOrdersScreenStrings(
    title = "Sequence Game (Orders)",
    instruction = "Connect each number on the left with its order name on the right. Select a number, then select its name to pair them.",
    units = "Units",
    tens = "Tens",
    hundreds = "Hundreds",
    thousands = "Thousands",
    tenThousands = "Ten Thousands",
    hundredThousands = "Hundred Thousands",
    millions = "Millions",
    tenMillions = "Ten Millions",
    hundredMillions = "Hundred Millions",
    billions = "Billions",
    newGame = "New Game",
    completionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFECT! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou matched all numbers with their order names!\nGreat job!",
    numberDescUnits = "is in the Units order, values between 0 and 9",
    numberDescTens = "is in the Tens order, values between 10 and 99",
    numberDescHundreds = "is in the Hundreds order, values between 100 and 999",
    numberDescThousands = "is in the Thousands order, values between 1,000 and 9,999",
    numberDescTenThousands = "is in the Ten Thousands order, values between 10,000 and 99,999",
    numberDescHundredThousands = "is in the Hundred Thousands order, values between 100,000 and 999,999",
    numberDescMillions = "is in the Millions order, values between 1,000,000 and 9,999,999",
    numberDescTenMillions = "is in the Ten Millions order, values between 10,000,000 and 99,999,999",
    numberDescHundredMillions = "is in the Hundred Millions order, values between 100,000,000 and 999,999,999",
    numberDescBillions = "is in the Billions order, values between 1,000,000,000 and 9,999,999,999",
    nameDescUnits = "Units are numbers in the range 0 and 9",
    nameDescTens = "Tens are numbers in the range 10 and 99",
    nameDescHundreds = "Hundreds are numbers in the range 100 and 999",
    nameDescThousands = "Thousands are numbers in the range 1,000 and 9,999",
    nameDescTenThousands = "Ten Thousands are numbers in the range 10,000 and 99,999",
    nameDescHundredThousands = "Hundred Thousands are numbers in the range 100,000 and 999,999",
    nameDescMillions = "Millions are numbers in the range 1,000,000 and 9,999,999",
    nameDescTenMillions = "Ten Millions are numbers in the range 10,000,000 and 99,999,999",
    nameDescHundredMillions = "Hundred Millions are numbers in the range 100,000,000 and 999,999,999",
    nameDescBillions = "Billions are numbers in the range 1,000,000,000 and 9,999,999,999",
)

val PtSequenceGameOrdersScreenStrings = SequenceGameOrdersScreenStrings(
    title = "Jogo da sequ\u00eancia (Ordens)",
    instruction = "Ligue cada n\u00famero \u00e0 esquerda ao nome de sua ordem \u00e0 direita. Selecione um n\u00famero e depois selecione seu nome para formar o par.",
    units = "Unidades",
    tens = "Dezenas",
    hundreds = "Centenas",
    thousands = "Milhares",
    tenThousands = "Dezenas de milhar",
    hundredThousands = "Centenas de milhar",
    millions = "Milh\u00f5es",
    tenMillions = "Dezenas de milh\u00f5es",
    hundredMillions = "Centenas de milh\u00f5es",
    billions = "Bilh\u00f5es",
    newGame = "Novo Jogo",
    completionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFEITO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea ligou todos os n\u00fameros \u00e0s suas ordens!\n\u00d3timo trabalho!",
    numberDescUnits = "est\u00e1 na ordem das unidades, valores entre 0 e 9",
    numberDescTens = "est\u00e1 na ordem das dezenas, valores entre 10 e 99",
    numberDescHundreds = "est\u00e1 na ordem das centenas, valores entre 100 e 999",
    numberDescThousands = "est\u00e1 na ordem dos milhares, valores entre 1.000 e 9.999",
    numberDescTenThousands = "est\u00e1 na ordem das dezenas de milhar, valores entre 10.000 e 99.999",
    numberDescHundredThousands = "est\u00e1 na ordem das centenas de milhar, valores entre 100.000 e 999.999",
    numberDescMillions = "est\u00e1 na ordem dos milh\u00f5es, valores entre 1.000.000 e 9.999.999",
    numberDescTenMillions = "est\u00e1 na ordem das dezenas de milh\u00f5es, valores entre 10.000.000 e 99.999.999",
    numberDescHundredMillions = "est\u00e1 na ordem das centenas de milh\u00f5es, valores entre 100.000.000 e 999.999.999",
    numberDescBillions = "est\u00e1 na ordem dos bilh\u00f5es, valores entre 1.000.000.000 e 9.999.999.999",
    nameDescUnits = "As unidades s\u00e3o n\u00fameros entre 0 e 9",
    nameDescTens = "As dezenas s\u00e3o n\u00fameros entre 10 e 99",
    nameDescHundreds = "As centenas s\u00e3o n\u00fameros entre 100 e 999",
    nameDescThousands = "Os milhares s\u00e3o n\u00fameros entre 1.000 e 9.999",
    nameDescTenThousands = "As dezenas de milhar s\u00e3o n\u00fameros entre 10.000 e 99.999",
    nameDescHundredThousands = "As centenas de milhar s\u00e3o n\u00fameros entre 100.000 e 999.999",
    nameDescMillions = "Os milh\u00f5es s\u00e3o n\u00fameros entre 1.000.000 e 9.999.999",
    nameDescTenMillions = "As dezenas de milh\u00f5es s\u00e3o n\u00fameros entre 10.000.000 e 99.999.999",
    nameDescHundredMillions = "As centenas de milh\u00f5es s\u00e3o n\u00fameros entre 100.000.000 e 999.999.999",
    nameDescBillions = "Os bilh\u00f5es s\u00e3o n\u00fameros entre 1.000.000.000 e 9.999.999.999",
)

val EsSequenceGameOrdersScreenStrings = SequenceGameOrdersScreenStrings(
    title = "Juego de secuencia (\u00d3rdenes)",
    instruction = "Conecta cada n\u00famero de la izquierda con el nombre de su orden de la derecha. Selecciona un n\u00famero y luego selecciona su nombre para formar la pareja.",
    units = "Unidades",
    tens = "Decenas",
    hundreds = "Centenas",
    thousands = "Miles",
    tenThousands = "Decenas de mil",
    hundredThousands = "Centenas de mil",
    millions = "Millones",
    tenMillions = "Decenas de millones",
    hundredMillions = "Centenas de millones",
    billions = "Mil millones",
    newGame = "Nuevo Juego",
    completionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1PERFECTO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n\u00a1Conectaste todos los n\u00fameros con sus \u00f3rdenes!\n\u00a1Gran trabajo!",
    numberDescUnits = "est\u00e1 en el orden de las unidades, valores entre 0 y 9",
    numberDescTens = "est\u00e1 en el orden de las decenas, valores entre 10 y 99",
    numberDescHundreds = "est\u00e1 en el orden de las centenas, valores entre 100 y 999",
    numberDescThousands = "est\u00e1 en el orden de los miles, valores entre 1.000 y 9.999",
    numberDescTenThousands = "est\u00e1 en el orden de las decenas de mil, valores entre 10.000 y 99.999",
    numberDescHundredThousands = "est\u00e1 en el orden de las centenas de mil, valores entre 100.000 y 999.999",
    numberDescMillions = "est\u00e1 en el orden de los millones, valores entre 1.000.000 y 9.999.999",
    numberDescTenMillions = "est\u00e1 en el orden de las decenas de millones, valores entre 10.000.000 y 99.999.999",
    numberDescHundredMillions = "est\u00e1 en el orden de las centenas de millones, valores entre 100.000.000 y 999.999.999",
    numberDescBillions = "est\u00e1 en el orden de los mil millones, valores entre 1.000.000.000 y 9.999.999.999",
    nameDescUnits = "Las unidades son n\u00fameros entre 0 y 9",
    nameDescTens = "Las decenas son n\u00fameros entre 10 y 99",
    nameDescHundreds = "Las centenas son n\u00fameros entre 100 y 999",
    nameDescThousands = "Los miles son n\u00fameros entre 1.000 y 9.999",
    nameDescTenThousands = "Las decenas de mil son n\u00fameros entre 10.000 y 99.999",
    nameDescHundredThousands = "Las centenas de mil son n\u00fameros entre 100.000 y 999.999",
    nameDescMillions = "Los millones son n\u00fameros entre 1.000.000 y 9.999.999",
    nameDescTenMillions = "Las decenas de millones son n\u00fameros entre 10.000.000 y 99.999.999",
    nameDescHundredMillions = "Las centenas de millones son n\u00fameros entre 100.000.000 y 999.999.999",
    nameDescBillions = "Los mil millones son n\u00fameros entre 1.000.000.000 y 9.999.999.999",
)

val LocalSequenceGameOrdersScreenStrings = staticCompositionLocalOf { EnSequenceGameOrdersScreenStrings }

fun sequenceGameOrdersScreenStringsForLanguage(language: String): SequenceGameOrdersScreenStrings = when (language) {
    "pt-BR" -> PtSequenceGameOrdersScreenStrings
    "es-ES" -> EsSequenceGameOrdersScreenStrings
    else -> EnSequenceGameOrdersScreenStrings
}
