// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class UiStrings(
    val home: String,
    val settings: String,
    val menu: String,
    val back: String,
    val open: String,
    val error: String,
    val language: String,
    val breakTime: String,
    val breakTimeDesc: String,
    val minutes: String,
    val all: String,
    val exercises: String,
    val yes: String,
    val no: String,
    val correct: String,
    val incorrect: String,
    val retry: String,
    val tryAgain: String,
    val score: String,
    val step: String,
    val previous: String,
    val next: String,
    val jump: String,
    val selectLevel: String,
    val answer: String,
    val birth: String,
    val death: String,
    val unknown: String,
    val iDontKnow: String,
)

val EnStrings = UiStrings(
    home = "Home",
    settings = "Settings",
    menu = "Menu",
    back = "Back",
    open = "Open",
    error = "Error",
    language = "Language",
    breakTime = "Break",
    breakTimeDesc = "Default break duration between study sessions",
    minutes = "minutes",
    all = "All",
    exercises = "Exercises",
    yes = "Yes",
    no = "No",
    correct = "Correct!",
    incorrect = "Incorrect",
    retry = "Retry",
    tryAgain = "Try Again",
    score = "Score",
    step = "Step",
    previous = "Previous",
    next = "Next",
    jump = "Jump",
    selectLevel = "Select Level",
    answer = "Answer",
    birth = "Birth",
    death = "Death",
    unknown = "?",
    iDontKnow = "I only know, I do not know...",
)

val PtStrings = UiStrings(
    home = "Principal",
    settings = "Op\u00e7\u00f5es",
    menu = "Menu",
    back = "Voltar",
    open = "Abrir",
    error = "Erro",
    language = "Idioma",
    breakTime = "Recreio",
    breakTimeDesc = "Dura\u00e7\u00e3o padr\u00e3o do intervalo entre sess\u00f5es de estudo",
    minutes = "minutos",
    all = "Todos",
    exercises = "Exerc\u00edcios",
    yes = "Sim",
    no = "N\u00e3o",
    correct = "Correto!",
    incorrect = "Incorreto",
    retry = "Tentar novamente",
    tryAgain = "Tentar novamente",
    score = "Pontua\u00e7\u00e3o",
    step = "Passo",
    previous = "Anterior",
    next = "Pr\u00f3ximo",
    jump = "Pular",
    selectLevel = "Selecionar N\u00edvel",
    answer = "Resposta",
    birth = "Nascimento",
    death = "Morte",
    unknown = "?",
    iDontKnow = "S\u00f3 sei que nada sei...",
)

val EsStrings = UiStrings(
    home = "Principal",
    settings = "Opciones",
    menu = "Men\u00fa",
    back = "Atr\u00e1s",
    open = "Abrir",
    error = "Error",
    language = "Idioma",
    breakTime = "Recreo",
    breakTimeDesc = "Duraci\u00f3n predeterminada del descanso entre sesiones de estudio",
    minutes = "minutos",
    all = "Todos",
    exercises = "Ejercicios",
    yes = "S\u00ed",
    no = "No",
    correct = "\u00a1Correcto!",
    incorrect = "Incorrecto",
    retry = "Reintentar",
    tryAgain = "Intentar de nuevo",
    score = "Puntuaci\u00f3n",
    step = "Paso",
    previous = "Anterior",
    next = "Siguiente",
    jump = "Saltar",
    selectLevel = "Seleccionar Nivel",
    answer = "Respuesta",
    birth = "Nacimiento",
    death = "Muerte",
    unknown = "?",
    iDontKnow = "Solo s\u00e9 que no s\u00e9 nada...",
) 

val LocalUiStrings = staticCompositionLocalOf { EnStrings }

fun uiStringsForLanguage(language: String): UiStrings = when (language) {
    "pt-BR" -> PtStrings
    "es-ES" -> EsStrings
    else -> EnStrings
}
