// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class UiStrings(
    val common: AppCommonStrings,
)

val EnStrings = UiStrings(
    common = AppCommonStrings(
        home = "Knowledge",
        settings = "Settings",
        menu = "Menu",
        back = "Back",
        open = "Open",
        error = "Error",
        language = "Language",
        breakTime = "Break",
        breakTimeDesc = "Default break duration between study sessions",
        minutes = "minutes",
        all = "All",
        exercises = "Exercises",
        yes = "Yes",
        no = "No",
        correct = "Correct!",
        incorrect = "Incorrect",
        retry = "Retry",
        tryAgain = "Try Again",
        score = "Score",
        step = "Step",
        previous = "Previous",
        next = "Next",
        jump = "Jump",
        selectLevel = "Select Level",
        answer = "Answer",
        unknown = "?",
        copyUrl = "Copy URL",
        goToUrl = "Go to URL",
        close = "Close",
        streak = "Streak",
        days = "days",
        breakReminderTitle = "Break Reminder",
        breakMessage = "You are doing an awesome work! But remember, relax is also part of the learning process. We suggest you to stop few minutes to drink water, go to the bathroom, talk with families, friends and relatives. Eat something before to proceed. When you return, click on \"I'm back!\" button to ensure you will receive another break reminder in few minutes.",
        imBack = "I'm back!",
        evaluateOn = "Evaluate on:",
        reminder = "Study Reminder",
        reminderTime = "Reminder time",
        reminderTitle = "Time to study!",
        reminderMessage = "Don't forget to do your exercises today.",
        ok = "OK",
        cancel = "Cancel",
        selectTime = "Select time",
        previousMonth = "Previous month",
        nextMonth = "Next month",
        skinColor = "Skin Color",
        value = "Value",
        reset = "Reset",
        resetDesc = "Clears all beads back to zero",
        write = "Write",
        level = "Level",
        levelComplete = "Congratulations, you finished level %d/8!",
        levelCompleteMax = "Congratulations, excellent work! You complete all levels",
        resetHint = "Click \"New Exercise\" to try another one!",
        nextLevel = "Next level",
        unsupportedContentType = "unsupported content type",
        levelPrefix = "Level: ",
        valuePrefix = "Value: ",
        stepPrefix = "Step ",
        newExercise = "New Exercise",
        nextStep = "Next Step",
        number = "Number:",
        auto = "Auto",
        stop = "Stop",
        complete = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 Complete! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89",
        sources = "Sources",
        originalText = "Original Text",
        imageOfflineMessage = "This image is only available when you are online.",
    ),
)

val PtStrings = UiStrings(
    common = AppCommonStrings(
        home = "Conhecimento",
        settings = "Op\u00e7\u00f5es",
        menu = "Menu",
        back = "Voltar",
        open = "Abrir",
        error = "Erro",
        language = "Idioma",
        breakTime = "Recreio",
        breakTimeDesc = "Dura\u00e7\u00e3o padr\u00e3o do intervalo entre sess\u00f5es de estudo",
        minutes = "minutos",
        all = "Todos",
        exercises = "Exerc\u00edcios",
        yes = "Sim",
        no = "N\u00e3o",
        correct = "Correto!",
        incorrect = "Incorreto",
        retry = "Tentar novamente",
        tryAgain = "Tentar novamente",
        score = "Pontua\u00e7\u00e3o",
        step = "Passo",
        previous = "Anterior",
        next = "Pr\u00f3ximo",
        jump = "Pular",
        selectLevel = "Selecionar N\u00edvel",
        answer = "Resposta",
        unknown = "?",
        copyUrl = "Copiar URL",
        goToUrl = "Ir para URL",
        close = "Fechar",
        streak = "Sequ\u00eancia",
        days = "dias",
        breakReminderTitle = "Lembrete de Pausa",
        breakMessage = "Voc\u00ea est\u00e1 fazendo um trabalho incr\u00edvel! Mas lembre-se, relaxar tamb\u00e9m faz parte do processo de aprendizagem. Sugerimos que voc\u00ea pare alguns minutos para beber \u00e1gua, ir ao banheiro, conversar com familiares, amigos e parentes. Coma algo antes de continuar. Quando voltar, clique no bot\u00e3o \"Voltei!\" para garantir que receber\u00e1 outro lembrete de pausa em alguns minutos.",
        imBack = "Voltei!",
        evaluateOn = "Avaliar em:",
        reminder = "Lembrete de Estudo",
        reminderTime = "Hor\u00e1rio do lembrete",
        reminderTitle = "Hora de estudar!",
        reminderMessage = "N\u00e3o se esque\u00e7a de fazer seus exerc\u00edcios hoje.",
        ok = "OK",
        cancel = "Cancelar",
        selectTime = "Selecionar hor\u00e1rio",
        previousMonth = "M\u00eas anterior",
        nextMonth = "Pr\u00f3ximo m\u00eas",
        skinColor = "Cor da Pele",
        value = "Valor",
        reset = "Reiniciar",
        resetDesc = "Limpa todas as contas, voltando ao zero",
        write = "Escreva",
        level = "N\u00edvel",
        levelComplete = "Parab\u00e9ns, voc\u00ea finalizou o n\u00edvel %d/8!",
        levelCompleteMax = "Parab\u00e9ns, excelente trabalho! Voc\u00ea completou todos os n\u00edveis",
        resetHint = "Clique em \"Novo Exerc\u00edcio\" para tentar outro!",
        nextLevel = "Pr\u00f3ximo n\u00edvel",
        unsupportedContentType = "tipo de conte\u00fado n\u00e3o suportado",
        levelPrefix = "N\u00edvel: ",
        valuePrefix = "Valor: ",
        stepPrefix = "Passo ",
        newExercise = "Novo Exerc\u00edcio",
        nextStep = "Pr\u00f3ximo Passo",
        number = "N\u00famero:",
        auto = "Autom\u00e1tico",
        stop = "Parar",
        complete = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 Completo! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89",
        sources = "Fontes",
        originalText = "Texto Original",
        imageOfflineMessage = "Esta imagem s\u00f3 est\u00e1 dispon\u00edvel quando voc\u00ea est\u00e1 online.",
    ),
)

val EsStrings = UiStrings(
    common = AppCommonStrings(
        home = "Conocimiento",
        settings = "Opciones",
        menu = "Men\u00fa",
        back = "Atr\u00e1s",
        open = "Abrir",
        error = "Error",
        language = "Idioma",
        breakTime = "Recreo",
        breakTimeDesc = "Duraci\u00f3n predeterminada del descanso entre sesiones de estudio",
        minutes = "minutos",
        all = "Todos",
        exercises = "Ejercicios",
        yes = "S\u00ed",
        no = "No",
        correct = "\u00a1Correcto!",
        incorrect = "Incorrecto",
        retry = "Reintentar",
        tryAgain = "Intentar de nuevo",
        score = "Puntuaci\u00f3n",
        step = "Paso",
        previous = "Anterior",
        next = "Siguiente",
        jump = "Saltar",
        selectLevel = "Seleccionar Nivel",
        answer = "Respuesta",
        unknown = "?",
        copyUrl = "Copiar URL",
        goToUrl = "Ir a URL",
        close = "Cerrar",
        streak = "Racha",
        days = "d\u00edas",
        breakReminderTitle = "Recordatorio de Descanso",
        breakMessage = "\u00a1Est\u00e1s haciendo un trabajo incre\u00edble! Pero recuerda, relajarse tambi\u00e9n es parte del proceso de aprendizaje. Te sugerimos que te detengas unos minutos para beber agua, ir al ba\u00f1o, hablar con familiares, amigos y parientes. Come algo antes de continuar. Cuando regreses, haz clic en el bot\u00f3n \"\u00a1Volv\u00ed!\" para asegurarte de recibir otro recordatorio de descanso en unos minutos.",
        imBack = "\u00a1Volv\u00ed!",
        evaluateOn = "Evaluar en:",
        reminder = "Recordatorio de Estudio",
        reminderTime = "Hora del recordatorio",
        reminderTitle = "\u00a1Hora de estudiar!",
        reminderMessage = "No olvides hacer tus ejercicios hoy.",
        ok = "OK",
        cancel = "Cancelar",
        selectTime = "Seleccionar hora",
        previousMonth = "Mes anterior",
        nextMonth = "Pr\u00f3ximo mes",
        skinColor = "Color de Piel",
        value = "Valor",
        reset = "Reiniciar",
        resetDesc = "Limpia todas las cuentas, volviendo a cero",
        write = "Escriba",
        level = "Nivel",
        levelComplete = "\u00a1Felicitaciones, terminaste el nivel %d/8!",
        levelCompleteMax = "\u00a1Felicitaciones, excelente trabajo! Completaste todos los niveles",
        resetHint = "\u00a1Haga clic en \"Nuevo Ejercicio\" para intentar otro!",
        nextLevel = "Siguiente nivel",
        unsupportedContentType = "tipo de contenido no soportado",
        levelPrefix = "Nivel: ",
        valuePrefix = "Valor: ",
        stepPrefix = "Paso ",
        newExercise = "Nuevo Ejercicio",
        nextStep = "Siguiente Paso",
        number = "N\u00famero:",
        auto = "Autom\u00e1tico",
        stop = "Parar",
        complete = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1Completo! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89",
        sources = "Fuentes",
        originalText = "Texto Original",
        imageOfflineMessage = "Esta imagen solo est\u00e1 disponible cuando est\u00e1s en l\u00ednea.",
    ),
)

val LocalUiStrings = staticCompositionLocalOf { EnStrings }

val LocalAppLanguage = staticCompositionLocalOf { "en-US" }

fun uiStringsForLanguage(language: String): UiStrings = when (language) {
    "pt-BR" -> PtStrings
    "es-ES" -> EsStrings
    else -> EnStrings
}
