// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui

data class AppCommonStrings(
    val home: String, val settings: String, val menu: String, val back: String,
    val open: String, val error: String, val language: String,
    val breakTime: String, val breakTimeDesc: String, val minutes: String,
    val all: String, val exercises: String, val yes: String, val no: String,
    val correct: String, val incorrect: String, val retry: String,
    val tryAgain: String, val score: String,
    val step: String, val previous: String, val next: String, val jump: String,
    val selectLevel: String, val answer: String, val unknown: String,
    val copyUrl: String, val goToUrl: String,
    val close: String, val streak: String, val days: String,
    val breakReminderTitle: String, val breakMessage: String, val imBack: String,
    val evaluateOn: String, val reminder: String,
    val reminderTime: String, val reminderTitle: String, val reminderMessage: String,
    val ok: String, val cancel: String, val selectTime: String,
    val previousMonth: String, val nextMonth: String, val skinColor: String,
    val value: String, val reset: String, val resetDesc: String,
    val write: String, val level: String, val levelComplete: String,
    val levelCompleteMax: String, val resetHint: String,
    val nextLevel: String,
    val unsupportedContentType: String,
    val levelPrefix: String, val valuePrefix: String,
    val stepPrefix: String, val newExercise: String,
    val nextStep: String, val number: String, val auto: String, val stop: String,
    val complete: String,
    val sources: String,
    val originalText: String,
)
