// SPDX-License-Identifier: GPL-3.0-or-later
package com.historytracers.app.ui

import androidx.compose.runtime.staticCompositionLocalOf

data class UiStrings(
    val common: AppCommonStrings,
    val titles: HubTitleStrings,
    val place: PlaceValueStrings,
    val body: BodyExerciseStrings,
    val abacusWrite: AbacusWriteStrings,
    val pa: PracticingAdditionStrings,
    val mw: MwStrings,
    val sbw: SbwStrings,
    val yupana: YupanaStrings,
    val misc: MiscStrings,
)

val EnStrings = UiStrings(
    common = AppCommonStrings(
        home = "Knowledge",
        settings = "Settings",
        menu = "Menu",
        back = "Back",
        open = "Open",
        error = "Error",
        language = "Language",
        breakTime = "Break",
        breakTimeDesc = "Default break duration between study sessions",
        minutes = "minutes",
        all = "All",
        exercises = "Exercises",
        yes = "Yes",
        no = "No",
        correct = "Correct!",
        incorrect = "Incorrect",
        retry = "Retry",
        runningAndGrowing = "Running and growing",
        tryAgain = "Try Again",
        score = "Score",
        step = "Step",
        previous = "Previous",
        next = "Next",
        jump = "Jump",
        selectLevel = "Select Level",
        answer = "Answer",
        unknown = "?",
        copyUrl = "Copy URL",
        goToUrl = "Go to URL",
        openApp = "Open App",
        close = "Close",
        streak = "Streak",
        days = "days",
        breakReminderTitle = "Break Reminder",
        breakMessage = "You are doing an awesome work! But remember, relax is also part of the learning process. We suggest you to stop few minutes to drink water, go to the bathroom, talk with families, friends and relatives. Eat something before to proceed. When you return, click on \"I'm back!\" button to ensure you will receive another break reminder in few minutes.",
        imBack = "I'm back!",
        voice = "Voice",
        evaluateOn = "Evaluate on:",
        reminder = "Study Reminder",
        reminderTime = "Reminder time",
        reminderTitle = "Time to study!",
        reminderMessage = "Don't forget to do your exercises today.",
        ok = "OK",
        cancel = "Cancel",
        selectTime = "Select time",
        previousMonth = "Previous month",
        nextMonth = "Next month",
        skinColor = "Skin Color",
        value = "Value",
        reset = "Reset",
        resetDesc = "Clears all beads back to zero",
        write = "Write",
        level = "Level",
        levelComplete = "Congratulations, you finished level %d/8!",
        levelCompleteMax = "Congratulations, excellent work! You complete all levels",
        resetHint = "Click \"New Exercise\" to try another one!",
        resetToZero = "Reset to 0",
        tracers = "Tracers",
        building = "Building",
        nextLevel = "Next level",
        numberOfClaps = "Number of claps:",
        unsupportedContentType = "unsupported content type",
        appNotInstalled = "App not installed",
        levelPrefix = "Level: ",
        valuePrefix = "Value: ",
        stepPrefix = "Step ",
        newExercise = "New Exercise",
        doExercise = "Do exercise",
        nextStep = "Next Step",
        number = "Number:",
        auto = "Auto",
        stop = "Stop",
        complete = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 Complete! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89",
        patreon = "Patreon",
        paypal = "PayPal",
        thinking = "Thinking",
        randomly = "Randomly",
        sources = "Sources",
        originalText = "Original Text",
        slowly = "Slowly",
        fast = "Fast",
    ),
    titles = HubTitleStrings(
        aRoadToSomewhere = "A road to somewhere",
        birth = "Birth",
        death = "Death",
        firstSteps = "First Steps (Counting)",
        workout = "Workout",
        abacus = "Abacus (Soroban/Suanpan)",
        iDontKnow = "I know that I know nothing",
        iAmNotLikeYou = "I am (not) like you",
        myHands = "My hands",
        myBody = "My body",
        drawing = "Drawing",
        numbers = "Numbers",
        sequenceGame = "Sequence game",
        familyPart1 = "Family (Part 1)",
        aboutUs = "About us",
        aboutDescription = "History Tracers is an open source project created to help people understand content instead of only exercising memorization.\n\nJoin our social network and share with us what subject you would like to have in all History Tracers apps.",
        isItFree = "Is it free?",
        isItFreeContent = "This project is not only free, but we also share the code with you, allowing you to learn how to create it as well.\n\nBut the fact that it is free does not mean it has no costs for us. We have expenses to maintain it, and it can grow faster when you contribute with ideas and, if possible, with financial support.",
        isItFreeDonateCall = "To support us, you can use one of our donation channels:",
        isItFreeFollowPrefix = "If you cannot, you do not need to feel bad, go to section below and follow us:",
        isItFreeFollowSuffix = "",
        history = "History",
        naturalFamiliesPart2 = "Natural Families (Part 2)",
        goingToInfinity = "Going to infinity",
        whereAreWeFrom = "Where are we from?",
        returning = "Returning",
        tomokoHoult = "Tomoko Hoult",
        aPal = "A-PAL",
        langEnUs = "English (US)",
        langPtBr = "Portugu\u00eas (BR)",
        langEsEs = "Espa\u00f1ol (ES)",
        congratulationTitle = "Congratulations!",
        congratulationMessage = "Congratulations on reaching this level! The previous classes are not locked, and you will not receive fewer points for studying them again. Every person has their own time to learn, and we respect that.\n\nWe are going to give you 10 points for reaching this level for the first time by completing everything before.\n\nEnjoy your own way of learning and your life, respecting yourself!",
        whoWalkFirst = "Who walked first?",
        whoWalkFirstButton = "?",
    ),
    place = PlaceValueStrings(
        levelUnits = "Units",
        levelTens = "Tens",
        levelHundreds = "Hundreds",
        levelThousands = "Thousands",
        levelTenThousands = "Ten Thousands",
        levelHundredThousands = "Hundred Thousands",
        levelMillions = "Millions",
        levelTenMillions = "Ten Millions",
        placeUnits = "units",
        placeTens = "tens",
        placeHundreds = "hundreds",
        placeThousands = "thousands",
        placeTenThousands = "ten thousands",
        placeHundredThousands = "hundred thousands",
        placeMillions = "millions",
        placeTenMillions = "ten millions",
        placeNext = "next",
    ),
    body = BodyExerciseStrings(
        clapInstructions = "Choose the number of times the hands will clap. Then, choose the speed of the claps. Do it yourself with the app.",
        clapReinforce = "To reinforce counting, we are going to do an exercise with our hands. Follow the next instructions and see how numbers are connected to us.",
        feetAndHandsReinforce = "To reinforce counting, we are going to do an exercise with our feet and hands. Follow the next instructions and see how numbers are connected to us.",
        relationshipReinforce = "To reinforce multiplication, we are going to do an exercise relating numbers to body movements. Follow the exercise and see how numbers are connected to us.\n\nThe selector above allows you to choose which multiplication table to practice, and the speed slider adjusts the pace of the movements. Try to do the movements with your own body if you can \u2014 it is a great way to take care of your health as well.",
        feetAndHandsInstructions = "Choose the number of times the feet will step or jump, or the hands will clap. Then, choose the speed. Do it yourself with the app.",
        speedSlow = "Slow",
        speedFast = "Fast",
        clapSkinColorHint = "Also, if you wish, you can change the skin color of the hands to match your own by going to Menu \u2192 Options.",
        feetAndHandsSkinColorHint = "Also, if you wish, you can change the skin color of the hands and feet to match your own by going to Menu \u2192 Options.",
        clap = "Clap",
        steps = "Steps",
        jumps = "Jumps",
        numberOfClapsStepsJumps = "Number of claps, steps, or jumps:",
        clapCounter = "Claps:",
        stepsCounter = "Steps:",
        jumpsCounter = "Jumps:",
        clapCompletionMessage = "Great job! You finished the exercise. Change the number of claps and train again!",
        exercisingHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou finished the exercise!\nAdjust the number of claps, then click 'Play' to workout again!",
        exercisingFeetAndHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou finished the exercise!\nChange the number of claps and train again!",
        exercisingAdditionCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou finished the exercise!\nClick \"New Exercise\" to try a new problem.",
        exercisingAddition = "Exercising addition",
        exercisingAdditionInstruction = "We will add numbers with our body. First, clap the top number, then clap the bottom number. Finally, take steps for the result. If the result is greater than 9, take a jump when reaching 10.",
        addingTwoNumbers = "Adding two numbers",
        addingLargeNumbers = "Adding large numbers",
        exercisingHands = "Exercising hands",
        walking = "Walking",
        exercisingFeetAndHands = "Exercising Feet and Hands",
        exercisingMultiplication = "Exercising Multiplication",
        exercisingMultiplicationL2 = "Exercising Multiplication (L2)",
        exercisingMultiplicationL2Description = "In this exercise, the 4 times table means both hands go up and down. The 5 times table adds a clap after the hands go up and down.\n\nThe up and down movement of both hands also shows that 4 is a multiple of 2, since the 2 movements (up and down) result in 4 total movements.\n\nSelect the multiplication table above, adjust the speed, and click \"Do Exercise\" to start. Try to do the movements with your own body as well!",
        relationship = "Relationship",
    ),
    abacusWrite = AbacusWriteStrings(
        writingToSoroban = "Writing to Soroban",
        writingToSuanpan = "Writing to Suanpan",
        writingLargeNumbers = "Writing large numbers",
        largeNumbers = "Large numbers",
        sorobanWritingInstruction = "This is the first in a series of texts that teach how to use the Soroban (\u7B97\u76E4). In this text, we will focus on the representation of numbers between 0 and 9; in future texts, we will learn how to use it more broadly. For now, we will only work with the first column from the right.\n\nThe marker on top (red) has value 5, while the marker below (blue) has value 1. Set the values as requested in the yellow box near the 'Value' box.",
        suanpanWritingInstruction = "This is the first in a series of texts that teach how to use the Suanpan (\u7B97\u76E4). In this text, we will focus on the representation of numbers between 0 and 9; in future texts, we will learn how to use it more broadly. For now, we will only work with the first column from the right.\n\nThe markers on top (red) have value 5 each, while the markers below (blue) have value 1 each. Set the values as requested in the yellow box near the 'Value' box.",
        largeNumbersWritingInstruction = "Practice representing large numbers (1 to 99,999,999) on both the Soroban (\u7B97\u76E4) and Suanpan (\u7B97\u76E4) simultaneously. Both abacuses share the same values. Use the 9 columns to represent units, tens, hundreds, and so on. Set the requested value shown in the yellow box using either abacus.",
        sorobanAbbr = "S",
        suanpanAbbr = "S",
        sorobanMode = "Soroban (1\u00D74)",
        suanpanMode = "Suanpan (2\u00D75)",
    ),
    pa = PracticingAdditionStrings(
        practicingAddition = "Practicing Addition",
        practicingAdditionInstruction = "Set the value shown in each step by tapping the beads on the abacus above. Complete all steps to finish the exercise.",
        stepWriteFirst = "Step 1: Write the first number %d in the abacus column(s) (%s).",
        stepAddTo = "Add to the %s: Add %d to the %s column. After this addition, the abacus should show %d.",
        stepCarrying = "Carrying 1: Adding %d to %s gives %d + %d = %d. Remove the complement %d from the %s column. Add 1 to the %s column. After these movements, the abacus should show %d.",
        stepFinal = "Final: %d + %d = %d. The abacus should show this sum!",
        feedbackPerfect = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFECT! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d + %d = %d\nGreat job using the abacus!",
        feedbackCorrect = "\u2705 Correct! Click 'Next step' to continue.",
        feedbackCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou calculated %d + %d = %d\nClick 'New exercise' to practice more!",
    ),
    mw = MwStrings(
        multiplyingWithAbacus = "12 x 3",
        multiplyingWithAbacusDescription = "Multiplying with Abacus",
        multiplyingWithAbacusInstruction = "Set the abacus to show each intermediate multiplication result by tapping the beads, following the step-by-step instructions below. Complete all steps to finish the multiplication.",
        mwStepPrefix = "\uD83E\uDDEE ",
        mwWelcomeMessage = "Click 'New Exercise' to start. Follow the instructions to arrange the abacus.",
        mwStepWriteFirst = "Step 1: Multiply the tens of %d by %d: %d \u00D7 %d = %d. Set the abacus to show %d.",
        mwUnitsProductHeader = "%d \u00D7 %d = %d. Therefore, ",
        mwStepAdd = "Add %d to the %s column. After this addition, the abacus should show %d.",
        mwStepCarry = "Carrying: Adding %d to %s gives %d + %d = %d (\u2265 10). Remove complement %d from %s and add 1 to %s. After these movements, the abacus should show %d.",
        mwStepFinal = "Final: %d \u00D7 %d = %d. The abacus should show this product!",
        mwCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou calculated %d \u00D7 %d = %d\nClick 'New exercise' to practice more!",
        mwStepStatus = "Step %d/%d",
        mwCorrectMessage = "\u2705 Correct! Click 'Next step' to continue.",
        mwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFECT! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u00D7 %d = %d\nGreat job using the abacus!",
        mwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered multiplication by %d! Click \"New exercise\" to start again at level 1.",
        mw2Title = "Multiplying with Abacus (Level 2)",
        mw2Description = "Multiplying with Abacus (Level 2)",
        mw3Title = "Multiplying without Limits",
        mwlInstruction = "Set the abacus to show each intermediate product by tapping the beads. Multiply by the tens digit, store the result, multiply by the ones digit, then add the stored value.",
        mwlShiftInstruction = "Shift left: %d \u2192 %d",
        mwlStoreInstruction = "Store %d",
        mwlResetInstruction = "Reset the abacus to 0",
        mwlAddStoredPrefix = "Add stored %d: ",
        mwlLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered two-digit multiplication! Click \"New exercise\" to start again at level 1.",
        mw2Instruction = "Set the abacus to show each intermediate multiplication result by tapping the beads, following the step-by-step instructions below. Complete all steps to finish the multiplication.",
        mw2StepWriteFirst = "Step 1: %d \u00D7 %d = %d. Set the abacus to show %d.",
        mw2LastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered all 8 levels! Click \"New exercise\" to start again at level 1.",
    ),
    sbw = SbwStrings(
        returningWithAbacus = "Returning with Abacus",
        subtractingWithAbacus = "Subtracting with Abacus",
        sbwTitle = "Practicing subtraction with the Soroban and the Suanpan (\u7B97\u76E4)",
        sbwInstruction = "Set the abacus to show the initial number, then subtract each digit of the subtrahend by tapping the beads. Complete all steps to finish the subtraction.",
        sbwStepPrefix = "\uD83E\uDDEE ",
        sbwSetupInstruction = "\uD83D\uDCCC Step 1: Set the abacus to show %d.",
        sbwSubStepInstruction = "%s After this change, the abacus should show %d.",
        sbwSubStepDesc = "\u2796 Subtract %d from the %s column.",
        sbwBorrowSetNine = "\u26A1 Since %s is 0, borrow from %s: set %s to 9 (we keep 9 here; the remaining value passes to the next column).",
        sbwBorrowReduce = "\u26A1 Borrow from %s (reduce from %d to %d). The value removed will be passed to the next column.",
        sbwBorrowSubUnits = "\u26A1 Add the complement %d (10 \u2212 %d = %d) to the %s column (%s becomes %d).",
        sbwFinalInstruction = "\uD83C\uDF89 Final: %d \u2212 %d = %d. The abacus should show this result!",
        sbwCorrectMessage = "\u2705 Correct! Click 'Next step' to continue.",
        sbwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFECT! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u2212 %d = %d\nGreat job using the abacus!",
        sbwCongratsMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou calculated %d \u2212 %d = %d\nClick 'New exercise' to practice more!",
        sbwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered subtraction! Click \"New exercise\" to start again at level 1.",
        sbwWelcomeMessage = "Click 'New exercise' to start. Follow the instructions to arrange the abacus.",
        sbwStepStatus = "\uD83D\uDCD6 Step %d/%d",
    ),
    yupana = YupanaStrings(
        yupana = "Yupana",
        quipu = "Quipu",
        handsOnYupana = "Hands on Yupana",
        movingInYupana = "Moving in Yupana",
        practicingWithYupana = "Practicing with the Yupana (Addition)",
        practicingAdditionYupanaInstruction = "To better understand the Yupana Inka Tawa Pukllay method, we will use a Yupana with 4 rows to add two numbers. With this configuration, we can represent values up to 4,999. However, it is possible to add more rows to add larger numbers, without limitations.\n\nIn the following example, we initially demonstrate the addition of 512 + 513. We invite you to switch between the three options to better understand the Yupana Inka Tawa Pukllay. Each option presents the following:\n- Values: shows how the numbers are written on the Yupana;\n- Result: shows the final result of the addition operation;\n- Step by Step: performs the addition row by row.\n\nYou can also modify the values in the example to reinforce your learning. After changing them, first click the Values button to display the numbers, and then see how they are represented on the Yupana.",
        yupanaValues = "Values",
        yupanaResult = "Result",
        yupanaStepByStep = "Step by Step",
        moves = "Moves",
        ypPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFECT! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d + %d = %d\nGreat job using the Yupana!",
        ypCorrectMessage = "\u2705 Correct! Click 'Next step' to continue.",
        ypAddTo = "Add to %s: %d + %d = %d. Place markers for %d in the Yupana.",
        ypAddToCarry = "Add to %s: %d + %d + %d (carry) = %d. Place markers for %d in the Yupana.",
        ypCarrying = "Carrying 1: Adding to %s gives %d + %d = %d (> 10). Place markers for %d in the Yupana. The carry will be added to %s in the next step.",
        ypCarryingCarry = "Carrying 1: Adding to %s gives %d + %d + %d (carry) = %d (> 10). Place markers for %d in the Yupana. The carry will be added to %s in the next step.",
        ypCongratsMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 CONGRATULATIONS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nYou calculated %d + %d = %d\nClick 'New exercise' to practice more!",
        ypLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 ALL LEVELS COMPLETE! \uD83C\uDFC6\uD83C\uDF89\nYou mastered all 9 levels! Click \"New exercise\" to start again at level 1.",
        ypRedPhase = "Place RED markers for %d in the %s.",
        ypBluePhase = "Place BLUE markers for %d in the %s.",
    ),
    misc = MiscStrings(
        multiplicationTable = "Multiplication Table",
        multiplicationTableDescription = "Select a number, then tap Auto to watch the abacus display each multiplication step, or tap Next Step to advance manually. Complete all 10 steps to finish.",
        abacusInOrdersReading = "1, 10,...",
        abacusInRereading = "Abacus in rereading",
    ),
)

val PtStrings = UiStrings(
    common = AppCommonStrings(
        home = "Conhecimento",
        settings = "Op\u00e7\u00f5es",
        menu = "Menu",
        back = "Voltar",
        open = "Abrir",
        error = "Erro",
        language = "Idioma",
        breakTime = "Recreio",
        breakTimeDesc = "Dura\u00e7\u00e3o padr\u00e3o do intervalo entre sess\u00f5es de estudo",
        minutes = "minutos",
        all = "Todos",
        exercises = "Exerc\u00edcios",
        yes = "Sim",
        no = "N\u00e3o",
        correct = "Correto!",
        incorrect = "Incorreto",
        retry = "Tentar novamente",
        runningAndGrowing = "Correndo e crescendo",
        tryAgain = "Tentar novamente",
        score = "Pontua\u00e7\u00e3o",
        step = "Passo",
        previous = "Anterior",
        next = "Pr\u00f3ximo",
        jump = "Pular",
        selectLevel = "Selecionar N\u00edvel",
        answer = "Resposta",
        unknown = "?",
        copyUrl = "Copiar URL",
        goToUrl = "Ir para URL",
        openApp = "Abrir App",
        close = "Fechar",
        streak = "Sequ\u00eancia",
        days = "dias",
        breakReminderTitle = "Lembrete de Pausa",
        breakMessage = "Voc\u00ea est\u00e1 fazendo um trabalho incr\u00edvel! Mas lembre-se, relaxar tamb\u00e9m faz parte do processo de aprendizagem. Sugerimos que voc\u00ea pare alguns minutos para beber \u00e1gua, ir ao banheiro, conversar com familiares, amigos e parentes. Coma algo antes de continuar. Quando voltar, clique no bot\u00e3o \"Voltei!\" para garantir que receber\u00e1 outro lembrete de pausa em alguns minutos.",
        imBack = "Voltei!",
        voice = "Voz",
        evaluateOn = "Avaliar em:",
        reminder = "Lembrete de Estudo",
        reminderTime = "Hor\u00e1rio do lembrete",
        reminderTitle = "Hora de estudar!",
        reminderMessage = "N\u00e3o se esque\u00e7a de fazer seus exerc\u00edcios hoje.",
        ok = "OK",
        cancel = "Cancelar",
        selectTime = "Selecionar hor\u00e1rio",
        previousMonth = "M\u00eas anterior",
        nextMonth = "Pr\u00f3ximo m\u00eas",
        skinColor = "Cor da Pele",
        value = "Valor",
        reset = "Reiniciar",
        resetDesc = "Limpa todas as contas, voltando ao zero",
        write = "Escreva",
        level = "N\u00edvel",
        levelComplete = "Parab\u00e9ns, voc\u00ea finalizou o n\u00edvel %d/8!",
        levelCompleteMax = "Parab\u00e9ns, excelente trabalho! Voc\u00ea completou todos os n\u00edveis",
        resetHint = "Clique em \"Novo Exerc\u00edcio\" para tentar outro!",
        resetToZero = "Reiniciar para 0",
        tracers = "Tracers",
        building = "Constru\u00e7\u00e3o",
        nextLevel = "Pr\u00f3ximo n\u00edvel",
        numberOfClaps = "N\u00famero de palmas:",
        unsupportedContentType = "tipo de conte\u00fado n\u00e3o suportado",
        appNotInstalled = "Aplicativo n\u00e3o instalado",
        levelPrefix = "N\u00edvel: ",
        valuePrefix = "Valor: ",
        stepPrefix = "Passo ",
        newExercise = "Novo Exerc\u00edcio",
        doExercise = "Fazer exerc\u00edcio",
        nextStep = "Pr\u00f3ximo Passo",
        number = "N\u00famero:",
        auto = "Autom\u00e1tico",
        stop = "Parar",
        complete = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 Completo! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89",
        patreon = "Patreon",
        paypal = "PayPal",
        thinking = "Pensando",
        randomly = "Aleat\u00f3rio",
        sources = "Fontes",
        originalText = "Texto Original",
        slowly = "Devagar",
        fast = "R\u00e1pido",
    ),
    titles = HubTitleStrings(
        aRoadToSomewhere = "Uma estrada para algum lugar",
        birth = "Nascimento",
        death = "Morte",
        firstSteps = "Primeiros Passos (Contando)",
        workout = "Exerc\u00edcio",
        abacus = "\u00c1baco (Soroban/Suanpan)",
        iDontKnow = "S\u00f3 sei que nada sei...",
        iAmNotLikeYou = "Eu (n\u00e3o) sou como voc\u00ea",
        myHands = "Minhas m\u00e3os",
        myBody = "Meu corpo",
        drawing = "Desenho",
        numbers = "N\u00fameros",
        sequenceGame = "Jogo da sequ\u00eancia",
        familyPart1 = "Fam\u00edlia (Parte 1)",
        aboutUs = "Sobre n\u00f3s",
        aboutDescription = "History Tracers \u00e9 um projeto de c\u00f3digo aberto criado para ajudar as pessoas a compreender o conte\u00fado, em vez de apenas exercitar a memoriza\u00e7\u00e3o.\n\nJunte-se \u00e0 nossa rede social e compartilhe conosco qual assunto voc\u00ea gostaria de ter em todos os aplicativos History Tracers.",
        isItFree = "\u00c9 gratuito?",
        isItFreeContent = "Este projeto n\u00e3o \u00e9 apenas gratuito, mas tamb\u00e9m compartilhamos o c\u00f3digo com voc\u00ea, permitindo que aprenda a cri\u00e1-lo tamb\u00e9m.\n\nMas o fato de ser gratuito n\u00e3o significa que n\u00e3o tenha custos para n\u00f3s. Temos despesas para mant\u00ea-lo, e ele pode crescer mais r\u00e1pido quando voc\u00ea contribui com ideias e, se poss\u00edvel, com apoio financeiro.",
        isItFreeDonateCall = "Para nos apoiar, use um de nossos canais de doa\u00e7\u00e3o:",
        isItFreeFollowPrefix = "Se n\u00e3o puder, n\u00e3o precisa se sentir mal, v\u00e1 at\u00e9 a se\u00e7\u00e3o abaixo e siga-nos:",
        isItFreeFollowSuffix = "",
        history = "Hist\u00f3ria",
        naturalFamiliesPart2 = "Fam\u00edlias Naturais (Parte 2)",
        goingToInfinity = "Indo ao infinito",
        whereAreWeFrom = "De onde somos?",
        returning = "Retornando",
        tomokoHoult = "Tomoko Hoult",
        aPal = "A-PAL",
        langEnUs = "Ingl\u00eas (EUA)",
        langPtBr = "Portugu\u00eas (BR)",
        langEsEs = "Espanhol (ES)",
        congratulationTitle = "Parab\u00e9ns!",
        congratulationMessage = "Parab\u00e9ns por alcan\u00e7ar este n\u00edvel! As aulas anteriores n\u00e3o est\u00e3o bloqueadas e voc\u00ea n\u00e3o receber\u00e1 menos pontos por estud\u00e1-las novamente. Cada pessoa tem seu pr\u00f3prio tempo para aprender, e n\u00f3s respeitamos isso.\n\nVamos dar a voc\u00ea 10 pontos por alcan\u00e7ar este n\u00edvel pela primeira vez, fazendo tudo o que veio antes.\n\nAproveite seu pr\u00f3prio jeito de aprender e sua vida, respeitando a si mesmo!",
        whoWalkFirst = "Quem andou primeiro?",
        whoWalkFirstButton = "?",
    ),
    place = PlaceValueStrings(
        levelUnits = "Unidades",
        levelTens = "Dezenas",
        levelHundreds = "Centenas",
        levelThousands = "Milhares",
        levelTenThousands = "Dezenas de Milhar",
        levelHundredThousands = "Centenas de Milhar",
        levelMillions = "Milh\u00f5es",
        levelTenMillions = "Dezenas de Milh\u00f5es",
        placeUnits = "unidades",
        placeTens = "dezenas",
        placeHundreds = "centenas",
        placeThousands = "milhares",
        placeTenThousands = "dezenas de milhar",
        placeHundredThousands = "centenas de milhar",
        placeMillions = "milh\u00f5es",
        placeTenMillions = "dezenas de milh\u00f5es",
        placeNext = "pr\u00f3xima",
    ),
    body = BodyExerciseStrings(
        clapInstructions = "Escolha o n\u00famero de vezes que as m\u00e3os v\u00e3o bater palmas. Depois, escolha a velocidade das palmas. Fa\u00e7a voc\u00ea mesmo com o aplicativo.",
        clapReinforce = "Para refor\u00e7ar a contagem, vamos fazer um exerc\u00edcio com nossas m\u00e3os. Siga as pr\u00f3ximas instru\u00e7\u00f5es e veja como os n\u00fameros est\u00e3o conectados a n\u00f3s.",
        feetAndHandsReinforce = "Para refor\u00e7ar a contagem, vamos fazer um exerc\u00edcio com nossos p\u00e9s e m\u00e3os. Siga as pr\u00f3ximas instru\u00e7\u00f5es e veja como os n\u00fameros est\u00e3o conectados a n\u00f3s.",
        relationshipReinforce = "Para refor\u00e7ar a multiplica\u00e7\u00e3o, vamos fazer um exerc\u00edcio relacionando n\u00fameros a movimentos corporais. Siga o exerc\u00edcio e veja como os n\u00fameros est\u00e3o conectados a n\u00f3s.\n\nO seletor acima permite escolher qual tabuada praticar, e o controle de velocidade ajusta o ritmo dos movimentos. Tente fazer os movimentos com seu pr\u00f3prio corpo se puder \u2014 \u00e9 uma \u00f3tima maneira de cuidar da sua sa\u00fade tamb\u00e9m.",
        feetAndHandsInstructions = "Escolha o n\u00famero de vezes que os p\u00e9s v\u00e3o pisar ou pular, ou as m\u00e3os v\u00e3o bater palmas. Depois, escolha a velocidade. Fa\u00e7a voc\u00ea mesmo com o aplicativo.",
        speedSlow = "Devagar",
        speedFast = "R\u00e1pido",
        clapSkinColorHint = "Al\u00e9m disso, se desejar, voc\u00ea pode alterar a cor da pele das m\u00e3os para combinar com a sua, indo em Menu \u2192 Op\u00e7\u00f5es.",
        feetAndHandsSkinColorHint = "Al\u00e9m disso, se desejar, voc\u00ea pode alterar a cor da pele das m\u00e3os e dos p\u00e9s para combinar com a sua, indo em Menu \u2192 Op\u00e7\u00f5es.",
        clap = "Palmas",
        steps = "Passos",
        jumps = "Pulos",
        numberOfClapsStepsJumps = "N\u00famero de palmas, passos ou pulos:",
        clapCounter = "Palmas:",
        stepsCounter = "Passos:",
        jumpsCounter = "Pulos:",
        clapCompletionMessage = "\u00d3timo trabalho! Voc\u00ea terminou o exerc\u00edcio. Mude o n\u00famero de palmas e treine novamente!",
        exercisingHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea terminou o exerc\u00edcio!\nAjuste o n\u00famero de palmas e clique em 'Play' para treinar novamente!",
        exercisingFeetAndHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea terminou o exerc\u00edcio!\nMude o n\u00famero de palmas e treine novamente!",
        exercisingAdditionCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea terminou o exerc\u00edcio!\nClique em \"Novo Exerc\u00edcio\" para tentar um novo problema.",
        exercisingAddition = "Exercitando adi\u00e7\u00e3o",
        exercisingAdditionInstruction = "Vamos somar n\u00fameros com o nosso corpo. Primeiro, bata palmas para o n\u00famero superior. Depois, bata palmas para o n\u00famero inferior. Por fim, d\u00ea passos para o resultado. Se o resultado for maior que 9, d\u00ea um pulo ao chegar em 10.",
        addingTwoNumbers = "Adicionando dois n\u00fameros",
        addingLargeNumbers = "Adicionando n\u00fameros grandes",
        exercisingHands = "Exercitando as m\u00e3os",
        walking = "Andando",
        exercisingFeetAndHands = "Exercitando P\u00e9s e M\u00e3os",
        exercisingMultiplication = "Exercitando Multiplica\u00e7\u00e3o",
        exercisingMultiplicationL2 = "Exercitando Multiplica\u00e7\u00e3o (L2)",
        exercisingMultiplicationL2Description = "Neste exerc\u00edcio, a tabuada do 4 significa que ambas as m\u00e3os sobem e descem. A tabuada do 5 adiciona uma palma ap\u00f3s as m\u00e3os subirem e descerem.\n\nO movimento de subir e descer de ambas as m\u00e3os tamb\u00e9m mostra que 4 \u00e9 um m\u00faltiplo de 2, j\u00e1 que os 2 movimentos (subir e descer) resultam em 4 movimentos no total.\n\nSelecione a tabuada acima, ajuste a velocidade e clique em \"Fazer Exerc\u00edcio\" para come\u00e7ar. Tente fazer os movimentos com seu pr\u00f3prio corpo tamb\u00e9m!",
        relationship = "Relacionamento",
    ),
    abacusWrite = AbacusWriteStrings(
        writingToSoroban = "Escrevendo no Soroban",
        writingToSuanpan = "Escrevendo no Suanpan",
        writingLargeNumbers = "Escrevendo n\u00fameros grandes",
        largeNumbers = "N\u00fameros grandes",
        sorobanWritingInstruction = "Este \u00e9 o primeiro de uma s\u00e9rie de textos que ensinam como usar o Soroban (\u7B97\u76E4). Neste texto, vamos nos concentrar na representa\u00e7\u00e3o dos n\u00fameros entre 0 e 9; em textos futuros, aprenderemos a us\u00e1-lo de forma mais ampla. Por enquanto, vamos trabalhar apenas com a primeira coluna da direita.\n\nO marcador superior (vermelho) tem valor 5, enquanto o marcador inferior (azul) tem valor 1. Defina os valores conforme solicitado na caixa amarela perto da caixa \"Valor\".",
        suanpanWritingInstruction = "Este \u00e9 o primeiro de uma s\u00e9rie de textos que ensinam como usar o Suanpan (\u7B97\u76E4). Neste texto, vamos nos concentrar na representa\u00e7\u00e3o dos n\u00fameros entre 0 e 9; em textos futuros, aprenderemos a us\u00e1-lo de forma mais ampla. Por enquanto, vamos trabalhar apenas com a primeira coluna da direita.\n\nOs marcadores superiores (vermelho) t\u00eam valor 5 cada, enquanto os marcadores inferiores (azul) t\u00eam valor 1 cada. Defina os valores conforme solicitado na caixa amarela perto da caixa \"Valor\".",
        largeNumbersWritingInstruction = "Pratique a representa\u00e7\u00e3o de n\u00fameros grandes (1 a 99.999.999) no Soroban (\u7B97\u76E4) e no Suanpan (\u7B97\u76E4) simultaneamente. Ambos os \u00e1bacos compartilham os mesmos valores. Use as 9 colunas para representar unidades, dezenas, centenas e assim por diante. Defina o valor solicitado na caixa amarela usando qualquer um dos \u00e1bacos.",
        sorobanAbbr = "S",
        suanpanAbbr = "S",
        sorobanMode = "Soroban (1\u00D74)",
        suanpanMode = "Suanpan (2\u00D75)",
    ),
    pa = PracticingAdditionStrings(
        practicingAddition = "Praticando Adi\u00e7\u00e3o",
        practicingAdditionInstruction = "Defina o valor mostrado em cada passo tocando nas contas do \u00e1baco acima. Complete todos os passos para finalizar o exerc\u00edcio.",
        stepWriteFirst = "Passo 1: Escreva o primeiro n\u00famero %d na(s) coluna(s) do \u00e1baco (%s).",
        stepAddTo = "Adicione \u00e0 %s: Adicione %d \u00e0 coluna %s. Ap\u00f3s esta adi\u00e7\u00e3o, o \u00e1baco deve mostrar %d.",
        stepCarrying = "Carregando 1: Adicionando %d \u00e0 %s resulta em %d + %d = %d. Remova o complemento %d da coluna %s. Adicione 1 \u00e0 coluna %s. Ap\u00f3s esses movimentos, o \u00e1baco deve mostrar %d.",
        stepFinal = "Final: %d + %d = %d. O \u00e1baco deve mostrar esta soma!",
        feedbackPerfect = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFEITO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d + %d = %d\n\u00d3timo trabalho usando o \u00e1baco!",
        feedbackCorrect = "\u2705 Correto! Clique em 'Pr\u00f3ximo passo' para continuar.",
        feedbackCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea calculou %d + %d = %d\nClique em 'Novo exerc\u00edcio' para praticar mais!",
    ),
    mw = MwStrings(
        multiplyingWithAbacus = "12 x 3",
        multiplyingWithAbacusDescription = "Multiplicando com \u00c1baco",
        multiplyingWithAbacusInstruction = "Configure o \u00e1baco para mostrar cada resultado intermedi\u00e1rio da multiplica\u00e7\u00e3o tocando nas contas, seguindo as instru\u00e7\u00f5es passo a passo abaixo. Complete todos os passos para finalizar a multiplica\u00e7\u00e3o.",
        mwStepPrefix = "\uD83E\uDDEE ",
        mwWelcomeMessage = "Clique em 'Novo Exerc\u00edcio' para iniciar. Siga as instru\u00e7\u00f5es para organizar o \u00e1baco.",
        mwStepWriteFirst = "Passo 1: Multiplique as dezenas de %d por %d: %d \u00D7 %d = %d. Coloque o \u00e1baco para mostrar %d.",
        mwUnitsProductHeader = "%d \u00D7 %d = %d. Portanto, ",
        mwStepAdd = "Adicione %d \u00e0 coluna %s. Ap\u00f3s esta adi\u00e7\u00e3o, o \u00e1baco deve mostrar %d.",
        mwStepCarry = "Levando 1: Adicionando %d a %s temos %d + %d = %d (\u2265 10). Remova o complemento %d de %s e adicione 1 a %s. Ap\u00f3s esses movimentos, o \u00e1baco deve mostrar %d.",
        mwStepFinal = "Final: %d \u00D7 %d = %d. O \u00e1baco deve mostrar este produto!",
        mwCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea calculou %d \u00D7 %d = %d\nClique em 'Novo exerc\u00edcio' para praticar mais!",
        mwStepStatus = "Passo %d/%d",
        mwCorrectMessage = "\u2705 Correto! Clique em 'Pr\u00f3ximo passo' para continuar.",
        mwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFEITO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u00D7 %d = %d\n\u00d3timo trabalho usando o \u00e1baco!",
        mwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou a multiplica\u00e7\u00e3o por %d! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
        mw2Title = "Multiplicando com \u00c1baco (N\u00edvel 2)",
        mw2Description = "Multiplicando com \u00c1baco (N\u00edvel 2)",
        mw3Title = "Multiplicando sem Limites",
        mwlInstruction = "Configure o \u00e1baco para mostrar cada produto intermedi\u00e1rio tocando nas contas. Multiplique pelo d\u00edgito das dezenas, armazene o resultado, multiplique pelo d\u00edgito das unidades e adicione o valor armazenado.",
        mwlShiftInstruction = "Desloque \u00e0 esquerda: %d \u2192 %d",
        mwlStoreInstruction = "Armazene %d",
        mwlResetInstruction = "Reinicialize o \u00e1baco para 0",
        mwlAddStoredPrefix = "Adicione o armazenado %d: ",
        mwlLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou a multiplica\u00e7\u00e3o por dois d\u00edgitos! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
        mw2Instruction = "Configure o \u00e1baco para mostrar cada resultado intermedi\u00e1rio da multiplica\u00e7\u00e3o tocando nas contas, seguindo as instru\u00e7\u00f5es passo a passo abaixo. Complete todos os passos para finalizar a multiplica\u00e7\u00e3o.",
        mw2StepWriteFirst = "Passo 1: %d \u00D7 %d = %d. Coloque o \u00e1baco para mostrar %d.",
        mw2LastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou todos os 8 n\u00edveis! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
    ),
    sbw = SbwStrings(
        returningWithAbacus = "Retornando com \u00c1baco",
        subtractingWithAbacus = "Subtraindo com \u00c1baco",
        sbwTitle = "Praticando subtra\u00e7\u00e3o com Soroban e Suanpan (\u7B97\u76E4)",
        sbwInstruction = "Coloque o \u00e1baco para mostrar o n\u00famero inicial e subtraia cada d\u00edgito do subtraendo tocando nas contas. Complete todos os passos para finalizar a subtra\u00e7\u00e3o.",
        sbwStepPrefix = "\uD83E\uDDEE ",
        sbwSetupInstruction = "\uD83D\uDCCC Passo 1: Coloque o \u00e1baco para mostrar %d.",
        sbwSubStepInstruction = "%s Ap\u00f3s esta mudan\u00e7a, o \u00e1baco dever\u00e1 mostrar %d.",
        sbwSubStepDesc = "\u2796 Subtraia %d da coluna das %s.",
        sbwBorrowSetNine = "\u26A1 Como %s \u00e9 0, empreste de %s: coloque %s em 9 (mantemos 9 aqui; o valor restante passa para a pr\u00f3xima coluna).",
        sbwBorrowReduce = "\u26A1 Pegue emprestado das %s (reduza de %d para %d). O valor retirado ser\u00e1 passado para a pr\u00f3xima coluna.",
        sbwBorrowSubUnits = "\u26A1 Adicione o complemento %d (10 \u2212 %d = %d) \u00e0 coluna de %s (%s se torna %d).",
        sbwFinalInstruction = "\uD83C\uDF89 Final: %d \u2212 %d = %d. O \u00e1baco dever\u00e1 mostrar este resultado!",
        sbwCorrectMessage = "\u2705 Correto! Clique em 'Pr\u00f3ximo passo' para continuar.",
        sbwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFEITO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u2212 %d = %d\n\u00d3timo trabalho usando o \u00e1baco!",
        sbwCongratsMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea calculou %d \u2212 %d = %d\nClique em 'Novo exerc\u00edcio' para praticar mais!",
        sbwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou a subtra\u00e7\u00e3o! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
        sbwWelcomeMessage = "Clique em 'Novo exerc\u00edcio' para iniciar. Siga as instru\u00e7\u00f5es para organizar o \u00e1baco.",
        sbwStepStatus = "\uD83D\uDCD6 Passo %d/%d",
    ),
    yupana = YupanaStrings(
        yupana = "Yupana",
        quipu = "Quipu",
        handsOnYupana = "M\u00e3os no Yupana",
        movingInYupana = "Movendo no Yupana",
        practicingWithYupana = "Exercitando com a Yupana (Adi\u00e7\u00e3o)",
        practicingAdditionYupanaInstruction = "Para compreender melhor o m\u00e9todo Yupana Inka Tawa Pukllay, utilizaremos uma Yupana com 4 linhas para somar dois n\u00fameros. Com essa configura\u00e7\u00e3o, podemos representar valores de at\u00e9 4.999. No entanto, \u00e9 poss\u00edvel adicionar mais linhas para somar n\u00fameros maiores, sem limita\u00e7\u00f5es.\n\nNo exemplo a seguir, demonstramos inicialmente a soma de 512 + 513. Convidamos voc\u00ea a alternar entre as tr\u00eas op\u00e7\u00f5es para compreender melhor o m\u00e9todo Yupana Inka Tawa Pukllay. Cada op\u00e7\u00e3o apresenta o seguinte:\n- Valores: mostra como os n\u00fameros s\u00e3o escritos na Yupana;\n- Calcular: mostra o resultado final da opera\u00e7\u00e3o de soma;\n- Passo a Passo: executa a soma linha por linha.\n\nVoc\u00ea tamb\u00e9m pode modificar os valores do exemplo para refor\u00e7ar seu aprendizado. Ap\u00f3s alter\u00e1-los, clique primeiro no bot\u00e3o Valores para exibir os n\u00fameros e, em seguida, veja como eles s\u00e3o representados na Yupana.",
        yupanaValues = "Valores",
        yupanaResult = "Calcular",
        yupanaStepByStep = "Passo a Passo",
        moves = "Movimentos",
        ypPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PERFEITO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d + %d = %d\n\u00d3timo trabalho usando a Yupana!",
        ypCorrectMessage = "\u2705 Correto! Clique em 'Pr\u00f3ximo passo' para continuar.",
        ypAddTo = "Adicione a %s: %d + %d = %d. Coloque marcadores para %d na Yupana.",
        ypAddToCarry = "Adicione a %s: %d + %d + %d (transporte) = %d. Coloque marcadores para %d na Yupana.",
        ypCarrying = "Carregando 1: Adicionar a %s resulta em %d + %d = %d (> 10). Coloque marcadores para %d na Yupana. O transporte ser\u00e1 adicionado a %s no pr\u00f3ximo passo.",
        ypCarryingCarry = "Carregando 1: Adicionar a %s resulta em %d + %d + %d (transporte) = %d (> 10). Coloque marcadores para %d na Yupana. O transporte ser\u00e1 adicionado a %s no pr\u00f3ximo passo.",
        ypCongratsMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 PARAB\u00c9NS! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nVoc\u00ea calculou %d + %d = %d\nClique em 'Novo exerc\u00edcio' para praticar mais!",
        ypLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 TODOS OS N\u00cdVEIS CONCLU\u00cdDOS! \uD83C\uDFC6\uD83C\uDF89\nVoc\u00ea dominou todos os 9 n\u00edveis! Clique em \"Novo exerc\u00edcio\" para come\u00e7ar novamente no n\u00edvel 1.",
        ypRedPhase = "Coloque marcadores VERMELHOS para %d na %s.",
        ypBluePhase = "Coloque marcadores AZUIS para %d na %s.",
    ),
    misc = MiscStrings(
        multiplicationTable = "Tabela de Multiplica\u00e7\u00e3o",
        multiplicationTableDescription = "Selecione um n\u00famero, depois toque em Autom\u00e1tico para ver o \u00e1baco mostrar cada passo da multiplica\u00e7\u00e3o, ou toque em Pr\u00f3ximo Passo para avan\u00e7ar manualmente. Complete todos os 10 passos para finalizar.",
        abacusInOrdersReading = "1, 10,...",
        abacusInRereading = "\u00c1baco na releitura",
    ),
)

val EsStrings = UiStrings(
    common = AppCommonStrings(
        home = "Conocimiento",
        settings = "Opciones",
        menu = "Men\u00fa",
        back = "Atr\u00e1s",
        open = "Abrir",
        error = "Error",
        language = "Idioma",
        breakTime = "Recreo",
        breakTimeDesc = "Duraci\u00f3n predeterminada del descanso entre sesiones de estudio",
        minutes = "minutos",
        all = "Todos",
        exercises = "Ejercicios",
        yes = "S\u00ed",
        no = "No",
        correct = "\u00a1Correcto!",
        incorrect = "Incorrecto",
        retry = "Reintentar",
        runningAndGrowing = "Corriendo y creciendo",
        tryAgain = "Intentar de nuevo",
        score = "Puntuaci\u00f3n",
        step = "Paso",
        previous = "Anterior",
        next = "Siguiente",
        jump = "Saltar",
        selectLevel = "Seleccionar Nivel",
        answer = "Respuesta",
        unknown = "?",
        copyUrl = "Copiar URL",
        goToUrl = "Ir a URL",
        openApp = "Abrir App",
        close = "Cerrar",
        streak = "Racha",
        days = "d\u00edas",
        breakReminderTitle = "Recordatorio de Descanso",
        breakMessage = "\u00a1Est\u00e1s haciendo un trabajo incre\u00edble! Pero recuerda, relajarse tambi\u00e9n es parte del proceso de aprendizaje. Te sugerimos que te detengas unos minutos para beber agua, ir al ba\u00f1o, hablar con familiares, amigos y parientes. Come algo antes de continuar. Cuando regreses, haz clic en el bot\u00f3n \"\u00a1Volv\u00ed!\" para asegurarte de recibir otro recordatorio de descanso en unos minutos.",
        imBack = "\u00a1Volv\u00ed!",
        voice = "Voz",
        evaluateOn = "Evaluar en:",
        reminder = "Recordatorio de Estudio",
        reminderTime = "Hora del recordatorio",
        reminderTitle = "\u00a1Hora de estudiar!",
        reminderMessage = "No olvides hacer tus ejercicios hoy.",
        ok = "OK",
        cancel = "Cancelar",
        selectTime = "Seleccionar hora",
        previousMonth = "Mes anterior",
        nextMonth = "Pr\u00f3ximo mes",
        skinColor = "Color de Piel",
        value = "Valor",
        reset = "Reiniciar",
        resetDesc = "Limpia todas las cuentas, volviendo a cero",
        write = "Escriba",
        level = "Nivel",
        levelComplete = "\u00a1Felicitaciones, terminaste el nivel %d/8!",
        levelCompleteMax = "\u00a1Felicitaciones, excelente trabajo! Completaste todos los niveles",
        resetHint = "\u00a1Haga clic en \"Nuevo Ejercicio\" para intentar otro!",
        resetToZero = "Reiniciar a 0",
        tracers = "Tracers",
        building = "Construcci\u00f3n",
        nextLevel = "Siguiente nivel",
        numberOfClaps = "N\u00famero de aplausos:",
        unsupportedContentType = "tipo de contenido no soportado",
        appNotInstalled = "Aplicaci\u00f3n no instalada",
        levelPrefix = "Nivel: ",
        valuePrefix = "Valor: ",
        stepPrefix = "Paso ",
        newExercise = "Nuevo Ejercicio",
        doExercise = "Hacer ejercicio",
        nextStep = "Siguiente Paso",
        number = "N\u00famero:",
        auto = "Autom\u00e1tico",
        stop = "Parar",
        complete = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1Completo! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89",
        patreon = "Patreon",
        paypal = "PayPal",
        thinking = "Pensando",
        randomly = "Aleatorio",
        sources = "Fuentes",
        originalText = "Texto Original",
        slowly = "Despacio",
        fast = "R\u00e1pido",
    ),
    titles = HubTitleStrings(
        aRoadToSomewhere = "Un camino a alg\u00fan lugar",
        birth = "Nacimiento",
        death = "Muerte",
        firstSteps = "Primeros Pasos (Contando)",
        workout = "Ejercicio",
        abacus = "\u00c1baco (Soroban/Suanpan)",
        iDontKnow = "Solo s\u00e9 que no s\u00e9 nada...",
        iAmNotLikeYou = "Yo (no) soy como t\u00fa",
        myHands = "Mis manos",
        myBody = "Mi cuerpo",
        drawing = "Dibujo",
        numbers = "N\u00fameros",
        sequenceGame = "Juego de secuencia",
        familyPart1 = "Familia (Parte 1)",
        aboutUs = "Sobre nosotros",
        aboutDescription = "History Tracers es un proyecto de c\u00f3digo abierto creado para ayudar a las personas a comprender el contenido, en lugar de solo ejercitar la memorizaci\u00f3n.\n\n\u00danete a nuestra red social y comparte con nosotros qu\u00e9 tema te gustar\u00eda tener en todas las aplicaciones de History Tracers.",
        isItFree = "\u00bfEs gratuito?",
        isItFreeContent = "Este proyecto no solo es gratuito, sino que tambi\u00e9n compartimos el c\u00f3digo contigo, permiti\u00e9ndote aprender a crearlo tambi\u00e9n.\n\nPero el hecho de que sea gratuito no significa que no tenga costos para nosotros. Tenemos gastos para mantenerlo, y puede crecer m\u00e1s r\u00e1pido cuando contribuyes con ideas y, si es posible, con apoyo financiero.",
        isItFreeDonateCall = "Para apoyarnos, usa uno de nuestros canales de donaci\u00f3n:",
        isItFreeFollowPrefix = "Si no puedes, no te sientas mal, ve a la secci\u00f3n de abajo y s\u00edguenos:",
        isItFreeFollowSuffix = "",
        history = "Historia",
        naturalFamiliesPart2 = "Familias Naturales (Parte 2)",
        goingToInfinity = "Yendo al infinito",
        whereAreWeFrom = "\u00bfDe d\u00f3nde somos?",
        returning = "Regresando",
        tomokoHoult = "Tomoko Hoult",
        aPal = "A-PAL",
        langEnUs = "Ingl\u00e9s (EE. UU.)",
        langPtBr = "Portugu\u00e9s (BR)",
        langEsEs = "Espa\u00f1ol (ES)",
        congratulationTitle = "\u00a1Felicitaciones!",
        congratulationMessage = "\u00a1Felicitaciones por alcanzar este nivel! Las clases anteriores no est\u00e1n bloqueadas y no recibir\u00e1s menos puntos por estudiarlas de nuevo. Cada persona tiene su propio tiempo para aprender, y respetamos eso.\n\nTe vamos a dar 10 puntos por alcanzar este nivel por primera vez, habiendo hecho todo lo anterior.\n\n\u00a1Disfruta tu propia forma de aprender y tu vida, respet\u00e1ndote a ti mismo!",
        whoWalkFirst = "\u00bfQui\u00e9n camin\u00f3 primero?",
        whoWalkFirstButton = "\u00bf?",
    ),
    place = PlaceValueStrings(
        levelUnits = "Unidades",
        levelTens = "Decenas",
        levelHundreds = "Centenas",
        levelThousands = "Miles",
        levelTenThousands = "Decenas de Millar",
        levelHundredThousands = "Centenas de Millar",
        levelMillions = "Millones",
        levelTenMillions = "Decenas de Millones",
        placeUnits = "unidades",
        placeTens = "decenas",
        placeHundreds = "centenas",
        placeThousands = "miles",
        placeTenThousands = "decenas de millar",
        placeHundredThousands = "centenas de millar",
        placeMillions = "millones",
        placeTenMillions = "decenas de millones",
        placeNext = "siguiente",
    ),
    body = BodyExerciseStrings(
        clapInstructions = "Elige el n\u00famero de veces que las manos aplaudir\u00e1n. Luego, elige la velocidad de los aplausos. Hazlo t\u00fa mismo con la aplicaci\u00f3n.",
        clapReinforce = "Para reforzar el conteo, vamos a hacer un ejercicio con nuestras manos. Sigue las siguientes instrucciones y observa c\u00f3mo los n\u00fameros est\u00e1n conectados con nosotros.",
        feetAndHandsReinforce = "Para reforzar el conteo, vamos a hacer un ejercicio con nuestros pies y manos. Sigue las siguientes instrucciones y observa c\u00f3mo los n\u00fameros est\u00e1n conectados con nosotros.",
        relationshipReinforce = "Para reforzar la multiplicaci\u00f3n, vamos a hacer un ejercicio relacionando n\u00fameros con movimientos corporales. Sigue el ejercicio y observa c\u00f3mo los n\u00fameros est\u00e1n conectados con nosotros.\n\nEl selector de arriba te permite elegir qu\u00e9 tabla de multiplicar practicar, y el control de velocidad ajusta el ritmo de los movimientos. Intenta hacer los movimientos con tu propio cuerpo si puedes \u2014 tambi\u00e9n es una excelente manera de cuidar tu salud.",
        feetAndHandsInstructions = "Elige el n\u00famero de veces que los pies pisar\u00e1n o saltar\u00e1n, o las manos aplaudir\u00e1n. Luego, elige la velocidad. Hazlo t\u00fa mismo con la aplicaci\u00f3n.",
        speedSlow = "Despacio",
        speedFast = "R\u00e1pido",
        clapSkinColorHint = "Adem\u00e1s, si lo deseas, puedes cambiar el color de piel de las manos para que coincida con la tuya, yendo a Men\u00fa \u2192 Opciones.",
        feetAndHandsSkinColorHint = "Adem\u00e1s, si lo deseas, puedes cambiar el color de piel de las manos y los pies para que coincida con el tuyo, yendo a Men\u00fa \u2192 Opciones.",
        clap = "Aplausos",
        steps = "Pasos",
        jumps = "Saltos",
        numberOfClapsStepsJumps = "N\u00famero de aplausos, pasos o saltos:",
        clapCounter = "Aplausos:",
        stepsCounter = "Pasos:",
        jumpsCounter = "Saltos:",
        clapCompletionMessage = "\u00a1Gran trabajo! Terminaste el ejercicio. \u00a1Cambia el n\u00famero de aplausos y entrena de nuevo!",
        exercisingHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n\u00a1Terminaste el ejercicio!\nAjusta el n\u00famero de aplausos y haz clic en 'Play' para entrenar de nuevo!",
        exercisingFeetAndHandsCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n\u00a1Terminaste el ejercicio!\n\u00a1Cambia el n\u00famero de aplausos y entrena de nuevo!",
        exercisingAdditionCompletionMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n\u00a1Terminaste el ejercicio!\nHaz clic en \"Nuevo Ejercicio\" para probar un nuevo problema.",
        exercisingAddition = "Ejercitando suma",
        exercisingAdditionInstruction = "Vamos a sumar n\u00fameros con nuestro cuerpo. Primero, aplaude el n\u00famero superior. Luego, aplaude el n\u00famero inferior. Finalmente, da pasos para el resultado. Si el resultado es mayor que 9, da un salto al llegar a 10.",
        addingTwoNumbers = "Sumando dos n\u00fameros",
        addingLargeNumbers = "Sumando n\u00fameros grandes",
        exercisingHands = "Ejercitando las manos",
        walking = "Caminando",
        exercisingFeetAndHands = "Ejercitando Pies y Manos",
        exercisingMultiplication = "Ejercitando Multiplicaci\u00f3n",
        exercisingMultiplicationL2 = "Ejercitando Multiplicaci\u00f3n (L2)",
        exercisingMultiplicationL2Description = "En este ejercicio, la tabla del 4 significa que ambas manos suben y bajan. La tabla del 5 a\u00f1ade un aplauso despu\u00e9s de que las manos suban y bajen.\n\nEl movimiento de subir y bajar de ambas manos tambi\u00e9n muestra que 4 es un m\u00faltiplo de 2, ya que los 2 movimientos (subir y bajar) resultan en 4 movimientos en total.\n\nSelecciona la tabla arriba, ajusta la velocidad y haz clic en \"Hacer Ejercicio\" para comenzar. \u00a1Intenta hacer los movimientos con tu propio cuerpo tambi\u00e9n!",
        relationship = "Relaci\u00f3n",
    ),
    abacusWrite = AbacusWriteStrings(
        writingToSoroban = "Escribiendo en el Soroban",
        writingToSuanpan = "Escribiendo en el Suanpan",
        writingLargeNumbers = "Escribiendo n\u00fameros grandes",
        largeNumbers = "N\u00fameros grandes",
        sorobanWritingInstruction = "Este es el primero de una serie de textos que ense\u00f1an c\u00f3mo usar el Soroban (\u7B97\u76E4). En este texto, nos centraremos en la representaci\u00f3n de n\u00fameros entre 0 y 9; en textos futuros, aprenderemos a usarlo de forma m\u00e1s amplia. Por ahora, solo trabajaremos con la primera columna de la derecha.\n\nEl marcador superior (rojo) tiene valor 5, mientras que el marcador inferior (azul) tiene valor 1. Establezca los valores seg\u00fan lo solicitado en el cuadro amarillo cerca del cuadro \"Valor\".",
        suanpanWritingInstruction = "Este es el primero de una serie de textos que ense\u00f1an c\u00f3mo usar el Suanpan (\u7B97\u76E4). En este texto, nos centraremos en la representaci\u00f3n de n\u00fameros entre 0 y 9; en textos futuros, aprenderemos a usarlo de forma m\u00e1s amplia. Por ahora, solo trabajaremos con la primera columna de la derecha.\n\nLos marcadores superiores (rojo) tienen valor 5 cada uno, mientras que los marcadores inferiores (azul) tienen valor 1 cada uno. Establezca los valores seg\u00fan lo solicitado en el cuadro amarillo cerca del cuadro \"Valor\".",
        largeNumbersWritingInstruction = "Practique la representaci\u00f3n de n\u00fameros grandes (1 a 99.999.999) en el Soroban (\u7B97\u76E4) y en el Suanpan (\u7B97\u76E4) simult\u00e1neamente. Ambos \u00e1bacos comparten los mismos valores. Use las 9 columnas para representar unidades, decenas, centenas y as\u00ed sucesivamente. Establezca el valor solicitado en el cuadro amarillo usando cualquiera de los \u00e1bacos.",
        sorobanAbbr = "S",
        suanpanAbbr = "S",
        sorobanMode = "Soroban (1\u00D74)",
        suanpanMode = "Suanpan (2\u00D75)",
    ),
    pa = PracticingAdditionStrings(
        practicingAddition = "Practicando Suma",
        practicingAdditionInstruction = "Establece el valor mostrado en cada paso tocando las cuentas del \u00e1baco de arriba. Completa todos los pasos para finalizar el ejercicio.",
        stepWriteFirst = "Paso 1: Escribe el primer n\u00famero %d en la(s) columna(s) del \u00e1baco (%s).",
        stepAddTo = "Agrega a %s: Agrega %d a la columna %s. Despu\u00e9s de esta suma, el \u00e1baco debe mostrar %d.",
        stepCarrying = "Llevando 1: Sumando %d a %s da %d + %d = %d. Retira el complemento %d de la columna %s. Agrega 1 a la columna %s. Despu\u00e9s de estos movimientos, el \u00e1baco debe mostrar %d.",
        stepFinal = "Final: %d + %d = %d. \u00a1El \u00e1baco debe mostrar esta suma!",
        feedbackPerfect = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1PERFECTO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d + %d = %d\n\u00a1Gran trabajo usando el \u00e1baco!",
        feedbackCorrect = "\u2705 \u00a1Correcto! Haz clic en 'Siguiente paso' para continuar.",
        feedbackCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nHas calculado %d + %d = %d\n\u00a1Haz clic en 'Nuevo ejercicio' para practicar m\u00e1s!",
    ),
    mw = MwStrings(
        multiplyingWithAbacus = "12 x 3",
        multiplyingWithAbacusDescription = "Multiplicando con \u00c1baco",
        multiplyingWithAbacusInstruction = "Configura el \u00e1baco para mostrar cada resultado intermedio de la multiplicaci\u00f3n tocando las cuentas, siguiendo las instrucciones paso a paso a continuaci\u00f3n. Completa todos los pasos para finalizar la multiplicaci\u00f3n.",
        mwStepPrefix = "\uD83E\uDDEE ",
        mwWelcomeMessage = "Haz clic en 'Nuevo Ejercicio' para comenzar. Sigue las instrucciones para organizar el \u00e1baco.",
        mwStepWriteFirst = "Paso 1: Multiplica las decenas de %d por %d: %d \u00D7 %d = %d. Coloca el \u00e1baco para mostrar %d.",
        mwUnitsProductHeader = "%d \u00D7 %d = %d. Por lo tanto, ",
        mwStepAdd = "A\u00f1ade %d a la columna %s. Despu\u00e9s de esta suma, el \u00e1baco debe mostrar %d.",
        mwStepCarry = "Llevando 1: Al a\u00f1adir %d a %s tenemos %d + %d = %d (\u2265 10). Quita el complemento %d de %s y a\u00f1ade 1 a %s. Despu\u00e9s de estos movimientos, el \u00e1baco debe mostrar %d.",
        mwStepFinal = "Final: %d \u00D7 %d = %d. \u00a1El \u00e1baco debe mostrar este producto!",
        mwCongratulations = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nHas calculado %d \u00D7 %d = %d\n\u00a1Haz clic en 'Nuevo ejercicio' para practicar m\u00e1s!",
        mwStepStatus = "Paso %d/%d",
        mwCorrectMessage = "\u2705 \u00a1Correcto! Haz clic en 'Siguiente paso' para continuar.",
        mwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1PERFECTO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u00D7 %d = %d\n\u00a1Gran trabajo usando el \u00e1baco!",
        mwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste la multiplicaci\u00f3n por %d! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
        mw2Title = "Multiplicando con \u00c1baco (Nivel 2)",
        mw2Description = "Multiplicando con \u00c1baco (Nivel 2)",
        mw3Title = "Multiplicando sin L\u00edmites",
        mwlInstruction = "Configura el \u00e1baco para mostrar cada producto intermedio tocando las cuentas. Multiplica por el d\u00edgito de las decenas, guarda el resultado, multiplica por el d\u00edgito de las unidades y suma el valor guardado.",
        mwlShiftInstruction = "Desplaza a la izquierda: %d \u2192 %d",
        mwlStoreInstruction = "Guarda %d",
        mwlResetInstruction = "Reinicia el \u00e1baco a 0",
        mwlAddStoredPrefix = "Suma el guardado %d: ",
        mwlLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste la multiplicaci\u00f3n por dos d\u00edgitos! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
        mw2Instruction = "Configura el \u00e1baco para mostrar cada resultado intermedio de la multiplicaci\u00f3n tocando las cuentas, siguiendo las instrucciones paso a paso a continuaci\u00f3n. Completa todos los pasos para finalizar la multiplicaci\u00f3n.",
        mw2StepWriteFirst = "Paso 1: %d \u00D7 %d = %d. Coloca el \u00e1baco para mostrar %d.",
        mw2LastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste los 8 niveles! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
    ),
    sbw = SbwStrings(
        returningWithAbacus = "Regresando con \u00c1baco",
        subtractingWithAbacus = "Restando con \u00c1baco",
        sbwTitle = "Practicando la resta con el Soroban y el Suanpan (\u7B97\u76E4)",
        sbwInstruction = "Coloca el \u00e1baco para mostrar el n\u00famero inicial y resta cada d\u00edgito del sustraendo tocando las cuentas. Completa todos los pasos para finalizar la resta.",
        sbwStepPrefix = "\uD83E\uDDEE ",
        sbwSetupInstruction = "\uD83D\uDCCC Paso 1: Coloca el \u00e1baco para mostrar %d.",
        sbwSubStepInstruction = "%s Despu\u00e9s de este cambio, el \u00e1baco deber\u00eda mostrar %d.",
        sbwSubStepDesc = "\u2796 Resta %d de la columna de las %s.",
        sbwBorrowSetNine = "\u26A1 Como %s es 0, pide prestado de %s: pon %s en 9 (mantenemos 9 aqu\u00ed; el valor restante pasa a la siguiente columna).",
        sbwBorrowReduce = "\u26A1 Pide prestado de las %s (reduce de %d a %d). El valor quitado ser\u00e1 pasado a la siguiente columna.",
        sbwBorrowSubUnits = "\u26A1 A\u00f1ade el complemento %d (10 \u2212 %d = %d) a la columna de %s (%s se convierte en %d).",
        sbwFinalInstruction = "\uD83C\uDF89 Final: %d \u2212 %d = %d. \u00a1El \u00e1baco deber\u00eda mostrar este resultado!",
        sbwCorrectMessage = "\u2705 \u00a1Correcto! Haz clic en 'Siguiente paso' para continuar.",
        sbwPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1PERFECTO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d \u2212 %d = %d\n\u00a1Gran trabajo usando el \u00e1baco!",
        sbwCongratsMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICIDADES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nHas calculado %d \u2212 %d = %d\n\u00a1Haz clic en 'Nuevo ejercicio' para practicar m\u00e1s!",
        sbwLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste la resta! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
        sbwWelcomeMessage = "Haz clic en 'Nuevo ejercicio' para comenzar. Sigue las instrucciones para organizar el \u00e1baco.",
        sbwStepStatus = "\uD83D\uDCD6 Paso %d/%d",
    ),
    yupana = YupanaStrings(
        yupana = "Yupana",
        quipu = "Quipu",
        handsOnYupana = "Manos en Yupana",
        movingInYupana = "Movi\u00e9ndose en Yupana",
        practicingWithYupana = "Ejercitando con la Yupana (Adici\u00f3n)",
        practicingAdditionYupanaInstruction = "Para comprender mejor el m\u00e9todo Yupana Inka Tawa Pukllay, utilizaremos una Yupana con 4 filas para sumar dos n\u00fameros. Con esta configuraci\u00f3n, podemos representar valores de hasta 4.999. Sin embargo, es posible agregar m\u00e1s filas para sumar n\u00fameros mayores, sin limitaciones.\n\nEn el siguiente ejemplo, demostramos inicialmente la suma de 512 + 513. Te invitamos a alternar entre las tres opciones para comprender mejor el m\u00e9todo Yupana Inka Tawa Pukllay. Cada opci\u00f3n presenta lo siguiente:\n- Valores: muestra c\u00f3mo se escriben los n\u00fameros en la Yupana;\n- Calcular: muestra el resultado final de la operaci\u00f3n de suma;\n- Paso a Paso: ejecuta la suma fila por fila.\n\nTambi\u00e9n puedes modificar los valores del ejemplo para reforzar tu aprendizaje. Despu\u00e9s de cambiarlos, haz clic primero en el bot\u00f3n Valores para mostrar los n\u00fameros y, a continuaci\u00f3n, observa c\u00f3mo se representan en la Yupana.",
        yupanaValues = "Valores",
        yupanaResult = "Calcular",
        yupanaStepByStep = "Paso a Paso",
        moves = "Movimientos",
        ypPerfectMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1PERFECTO! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\n%d + %d = %d\n\u00a1Gran trabajo usando la Yupana!",
        ypCorrectMessage = "\u2705 \u00a1Correcto! Haz clic en 'Siguiente paso' para continuar.",
        ypAddTo = "Agrega a %s: %d + %d = %d. Coloca marcadores para %d en la Yupana.",
        ypAddToCarry = "Agrega a %s: %d + %d + %d (llevada) = %d. Coloca marcadores para %d en la Yupana.",
        ypCarrying = "Llevando 1: Agregar a %s da %d + %d = %d (> 10). Coloca marcadores para %d en la Yupana. La llevada se agregar\u00e1 a %s en el siguiente paso.",
        ypCarryingCarry = "Llevando 1: Agregar a %s da %d + %d + %d (llevada) = %d (> 10). Coloca marcadores para %d en la Yupana. La llevada se agregar\u00e1 a %s en el siguiente paso.",
        ypCongratsMessage = "\uD83C\uDF89\uD83C\uDF89\uD83C\uDF89 \u00a1FELICITACIONES! \uD83C\uDF89\uD83C\uDF89\uD83C\uDF89\nHas calculado %d + %d = %d\n\u00a1Haz clic en 'Nuevo ejercicio' para practicar m\u00e1s!",
        ypLastLevelMessage = "\uD83C\uDF89\uD83C\uDFC6 \u00a1TODOS LOS NIVELES COMPLETADOS! \uD83C\uDFC6\uD83C\uDF89\n\u00a1Dominaste los 9 niveles! Haz clic en \"Nuevo ejercicio\" para empezar de nuevo en el nivel 1.",
        ypRedPhase = "Coloca marcadores ROJOS para %d en %s.",
        ypBluePhase = "Coloca marcadores AZULES para %d en %s.",
    ),
    misc = MiscStrings(
        multiplicationTable = "Tabla de Multiplicar",
        multiplicationTableDescription = "Selecciona un n\u00famero, luego toca Autom\u00e1tico para ver el \u00e1baco mostrar cada paso de la multiplicaci\u00f3n, o toca Siguiente Paso para avanzar manualmente. Completa los 10 pasos para finalizar.",
        abacusInOrdersReading = "1, 10,...",
        abacusInRereading = "\u00c1baco en relectura",
    ),
)

val LocalUiStrings = staticCompositionLocalOf { EnStrings }

fun uiStringsForLanguage(language: String): UiStrings = when (language) {
    "pt-BR" -> PtStrings
    "es-ES" -> EsStrings
    else -> EnStrings
}
